### ISSUE TITLE
Maintain writer.js or not?

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#109]
Looking at the git logs, the `ws: true` option is to enable the writing feature. It will be great to write a whitespace test with the writer (as we can just parse, write, and check the text is intact) but writer.js is currently not being maintained anymore. Should we maintain it or not?

**Comment by marcoscaceres** [comment]
Yeah, we should probably maintain it.

**Comment by saschanaz** [comment]
My original reason to maintain the writer seems circular.

1. `ws: true` is for writer.js
2. writer.js eases test for `ws: true`
3. So maintain them?

The writer really seems to be a formatter (as `ws: true` stores whitespaces selectively), currently I don't have a strong reason to maintain a WebIDL formatter.

**Comment by saschanaz** [comment]
Creating a WebIDL extension for VSCode with formatting feature may be fun, though :smile:

**Comment by Zirro** [comment]
I have a use case where I need to parse IDL, make a few changes to the AST and print it back out with the original formatting intact.

While I'm currently not able to use writer.js for this due to a few problems with the output (in addition to the selective whitespace retention mentioned earlier), a maintained writer.js would be very helpful for this purpose.

**Comment by saschanaz** [comment]
@Zirro Thank you for sharing your use case! Could I ask you the purpose of making those AST changes?

**Comment by Zirro** [comment]
@saschanaz Sure, it is for an IDL differ/merger to be used while developing [jsdom](https://github.com/tmpvar/jsdom). The tool would make it possible to compare and merge our current IDL files against the latest spec, while ignoring/restoring the changes we have made such as adding custom extended attributes or placing unimplemented properties behind comments.

After doing a few too many manual changes as part of https://github.com/tmpvar/jsdom/pull/2053, I hope to fully automate the process the next time.

**Comment by saschanaz** [comment]
So it seems we should reconsider how `ws: true` works. @marcoscaceres Thoughts?

**Comment by marcoscaceres** [comment]
I'm not fully understanding what @Zirro needs exactly, but I'm happy for us to enhance or change "ws" to accept additional options if need be :)

**Comment by saschanaz** [comment]
The parser should provide an option to store every whitespace it meets so that one can reconstruct the whole original IDL text with the parsed result. This way one may programmatically modify some IDL types without losing whitespaces.

**Comment by marcoscaceres** [comment]
Oh, I was under the impression it was already doing that. If "`ws: true` doesn't do that, then that's a bug and we should treat it as such.

**Comment by saschanaz** [comment]
Currently `all_ws()` without arguments throws away all tokens it meets.

**Comment by saschanaz** [comment]
Currently `all_ws()` without arguments throws away all whitespace tokens it meets. And I think it was on purpose, probably to create a formatter.

**Comment by marcoscaceres** [comment]
Will release soon. Travelling atm.

**Comment by saschanaz** [comment]
It's currently not being exposed for Node package, so probably no need to release this time.
