### ISSUE TITLE
Improve "No semicolon after enum" message

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#119]
Would be great if we could improve "No semicolon after enum" to "Missing semicolon after ${identifier} enum".

**Comment by saschanaz** [comment]
Currently errors have no context information, we may create a general way to give one automatically.

**Comment by marcoscaceres** [comment]
I guess maybe #85 (parent) would again come into play - but having it removed when JSON-serializing.

**Comment by saschanaz** [comment]
Not sure how #85 helps for the semicolon-missing error, can you give an example?

I was thinking indentation-based error message:

```webidl
enum MyEnum { // indentation 0
  "hm", // indentation added, store the last less-indented parent line
  "md",
} // indentation returns to 0, guess it's closing, still remember the opener line

interface A { } // error here, we can emit enum opener and closer in the error message
```

**Comment by marcoscaceres** [comment]
Sorry, I meant `parent` would help identify "MyEnum" as identifier, similarly with "A". However, you are probably right that `parent` wouldn't help there... I should have looked at how that part of the parser works.
