### ISSUE TITLE
Support full whitespace conservation

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#125]
Currently, e.g.

```
TypeA /* Hi, I'm a comment */ includes          TypeB
```

automatically becomes `TypeA includes TypeB` even with `ws: true`, as both parser and writer do not support full whitespace conservation.

**Comment by marcoscaceres** [comment]
I ran into this too. It's an edge case but we should add it.

**Comment by saschanaz** [comment]
Current plan (changes expected): introduce a new field named `trivia`.

1. An IDL definition has a `trivia` field that includes preceding whitespaces/comments of required tokens:

```json
{
  "trivia": {
    "base": "// The following is an interface type\n",
    "name": " /* I'm a comment between the word `interface` and the interface name */ ",
    "open": " ",
    "close": "\n"
  }
}
```

2. An optional feature is expressed as an object instead of boolean, again including a `trivia` field.

```
{
  "partial": {
    "trivia": " "
  },
  // "partial": null when not partial
}
```

3. Members also has its own `trivia` field.

**Comment by marcoscaceres** [comment]
trivia seems fine/fun :)
