### ISSUE TITLE
Support `legacycaller`

### ISSUE THREAD

**Issue by snyderp** [w3c/webidl2.js#127]
Some published WebIDL standards use the `legacycaller` type (ex https://www.w3.org/TR/html51/infrastructure.html#the-htmlallcollection-interface).  It would be nice to be able to parse these definitions.

FWIW, here is a chromium bug for the same issue (though the links they point to don't seem to use the token anymore).
https://bugs.chromium.org/p/chromium/issues/detail?id=465009

There are many such examples in the published IDL Index
https://www.w3.org/TR/html51/idl-index.html#idl-index

Currently text like 

```
interface HTMLAllCollection {
  readonly attribute unsigned long length;
  getter Element? (unsigned long index);
  getter (HTMLCollection or Element)? namedItem(DOMString name);
  legacycaller (HTMLCollection or Element)? item(optional DOMString nameOrItem);
};
```
gives

```
Error: Unterminated operation, line 6 (tokens: 'Element)? item')
[
    {
        "type": "identifier",
        "value": "Element"
    },
    {
        "type": "other",
        "value": ")"
    },
    {
        "type": "other",
        "value": "?"
    },
    {
        "type": "whitespace",
        "value": " "
    },
    {
        "type": "identifier",
        "value": "item"
    }
]
```

**Comment by marcoscaceres** [comment]
Weird that it works for the `getter`, but not for `legacycaller`. I guess it would be trivial to get it to parse that, given that it works with the `getter`.

**Comment by marcoscaceres** [comment]
Actually, this one is not valid either. For HTML, please use the WHATWG version. The W3C version is obsolete.

**Comment by marcoscaceres** [comment]
(just noting that `legacycaller` is also no longer part of the IDL spec)

**Comment by marcoscaceres** [comment]
@snyderp - an option for you might be to downgrade WebIDL parser for certain specs?
