### ISSUE TITLE
Support `raises` and `setraises`

### ISSUE THREAD

**Issue by snyderp** [w3c/webidl2.js#128]
I cannot find any definition for it in the WebIDL standard, but many W3C standards use raises and set raises to indication exceptions that operations throw.

For example, the [SVG 1.1 standard](https://www.w3.org/TR/SVG/idl.html) has lots of lines like
```
interface SVGElement : Element {
           attribute DOMString id setraises(DOMException);
           attribute DOMString xmlbase setraises(DOMException);
  readonly attribute SVGSVGElement ownerSVGElement;
  readonly attribute SVGElement viewportElement;
};
```

and older versions of the DOM standards (1 through 3) use it too.  For example https://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/idl-definitions.html lines like

```
  interface DOMImplementation {
    boolean            hasFeature(in DOMString feature, 
                                  in DOMString version);
    // Introduced in DOM Level 2:
    DocumentType       createDocumentType(in DOMString qualifiedName, 
                                          in DOMString publicId, 
                                          in DOMString systemId)
                                        raises(DOMException);
    // Introduced in DOM Level 2:
    Document           createDocument(in DOMString namespaceURI, 
                                      in DOMString qualifiedName, 
                                      in DocumentType doctype)
                                        raises(DOMException);
  };
```

(the above example also won't parse b/c of the `in` items, but thats a different issue / request :) )

**Comment by marcoscaceres** [comment]
Those obsolete specs are using OMG IDL. The right spec to use for DOM is http://dom.spec.whatwg.org

**Comment by saschanaz** [comment]
Note that SVG 2 has valid Web IDLs 😁
