### ISSUE TITLE
Meta - conforming Web IDL validator

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#138]
This bug is for planning... 

It would be really interesting to have webidl2.js be a validating parser... that is, one that checks the conformance requirements from the WebIDL spec and either warns, blows up, and/or collects errors/warnings.

**Comment by saschanaz** [comment]
This can also be covered: https://github.com/w3c/respec/issues/1184

**Comment by kenrussell** [comment]
What are the project owners' thoughts on how to get started on a large project like this?

In the WebGL project there is a longstanding issue https://github.com/KhronosGroup/WebGL/issues/2216 where the IDL is invalid, but I couldn't find a Web IDL parser that validates the Editor's Draft version of the spec ( https://heycam.github.io/webidl/ ).

Personally I'd like to contribute to webidl2.js, as writing the validation rules in [XML](https://github.com/dontcallmedom/webidl-checker/blob/master/widlproc-schematron/webidl-schematron.xml) doesn't sound fun.

Can you provide some ideas or framework under which validation rules can be contributed in a scalable manner by multiple individuals?

**Comment by saschanaz** [comment]
IMO the implementation will be in JS with corresponding tests, with API like: `parse(text, { validate: true })`. The option `validate` should include the existing conformance check in #80, which then will be optional.

We have a very vague plan, and I think we should start with anything and then make some progress over it, including code readability optimization.

**Comment by marcoscaceres** [comment]
Agree, but I'd like see some kind proposed structure for error reporting and done in an extensible way. I'd like us to consider: 
 
  * non-validating parser (basically what we have today, except for syntax errors).
  * validating parser (validates as it parsers, throws on errors? or reports/emits errors?).
  * output validator: runs non-validating parser, but then we can validate the output (i.e., `validate(parse(idl))`).

From ReSpec's perspective, the last option might be good, because it means we can still render parsed output, even if it's full of validation errors. 

The drawback of the final option is the loss of context (line numbers, for example). So, maybe we want something in the middle:

```JS
const idlObj = parse(text);
const { idl, errors } = parse(text, {validate: true));
```

`errors` would be validation errors that are non-fatal. We might need to change how the code currently works, because I think we throw a the moment for various things. 

There are tradeoffs for each. We would also need to refactor quite a bit of code, as the parser/validation aspects could lead to quite complex code, given the current code structure (i.e., we might need to split things up a bit more).

**Comment by kenrussell** [comment]
Changing the parser to be validating sounds like it would be intrusive.

If validation happened after parsing, people would probably be able to infer on which line validation errors happened based on the names of the identifiers printed in the error messages; what do you think?

**Comment by marcoscaceres** [comment]
> If validation happened after parsing, people would probably be able to infer on which line validation errors happened based on the names of the identifiers printed in the error messages; what do you think?

Yeah, this is true. The problem is that some IDL files can be thousands of lines (extreme example):
https://github.com/w3c/web-platform-tests/blob/master/interfaces/html.idl

Giving enough context (e.g., "Validation error: The Foo interface is an interface, hence can't have a Y thing!") might be sufficient. In ReSpec, that's not a problem, because lines are meaningless. 

However, in other contexts where WebIDL2.js is used, it might be a problem (e.g., if you hook it up into text editor like visual studio)

**Comment by saschanaz** [comment]
>const { idl, errors } = parse(text, {validate: true));

How about validate by default, and optionally turn it off? Because probably we want to be strict by default...

```
const { idl, errors } = parse(text, { noValidate: true )); // `errors` will be an empty array
```

>Changing the parser to be validating sounds like it would be intrusive.

This may be a potential problem, but we don't know before actually trying it, right? A pioneering PR will be great to start more active discussion.

My vague thought: we may first create `validateExtAttr(parent, extattrs);` and call it in proper positions.

**Comment by saschanaz** [comment]
Alternatively, we may memorize text positions of each type definition and use it when postpass. Sounds good enough to me.

**Comment by saschanaz** [comment]
So my updated thought:

```js
import { parse, validate } from "webidl2";
var str;
let result = parse(str); // Validate by default, by internally calling validate() after parsing.

console.log(result[0].line, result[0].column); // Gives position by line/column. This info will be used to generate postpass validation error messages

result = parse(str, { noValidate: true });
result = modify(result); // someone wants to modify AST
validate(result);
```

**Comment by marcoscaceres** [comment]
> result = parse(str, { noValidate: true }); // Do we want this? What would be the use case?

Perhaps a fast path? don't traverse validator code. Or, don't want it to throw on non-syntax things (e.g., `record<SomeInterface, SomeOtherInterface>`, which is not allowed, but syntactically valid).

**Comment by saschanaz** [comment]
Can I open a PR for `validate()` and `noValidate: true`? Or any objection?

**Comment by marcoscaceres** [comment]
Sure, go for it @saschanaz. @kenrussell, if you would like to collaborate on this, we are certainly open to it. 

However, we need to chat a bit about architecture for it. Ideally, we would put in place something that is pluggable, so we can incrementally add things to the validator (`validateInterface()`, `valiadateAttribute()` and so on... no idea what this will look like, but something like that).

**Comment by saschanaz** [comment]
Should those functions be in a separate module? Currently webidl2.js is a single UMD module that can also work in a browser context without any module system.

**Comment by marcoscaceres** [comment]
> Should those functions be in a separate module?

It's not necessary that they be in another module, just that that there validation doesn't get intertwined into the parser (i.e., can call out into smaller functions). The parser is already quite complicated, so want to make sure it doesn't become (more) spaghetti.

**Comment by saschanaz** [comment]
I would start by splitting the existing duplicate name checker into validation functions.

**Comment by saschanaz** [comment]
IDL texts are typically split into several parts, should the conformance checker be able to receive multiple ASTs?

```js
const ast1 = parse();
const ast2 = parse();
validate(ast1, ast2); // error: ast1 and ast2 have a duplicated name!
```

**Comment by marcoscaceres** [comment]
As long as the caller can figure out there is duplication in the things they send in, I think using the array is fine. However, it might be one of those things we might need to try out.

**Comment by saschanaz** [comment]
We now have a powerful writer that can hook for many things. Maybe we can use that power to make a validator, but getting the line numbers are still the problem...

**Comment by marcoscaceres** [comment]
Doing line number later seems fine.

**Comment by saschanaz** [comment]
BTW I'm considering a major code change for line numbers, for example:

```
export class Operation {
  parent = parentInterface;
  tokens; // parsed tokens from the input text, also contains position from text

  /* ... some existing attributes ... */

  toString(); // returns original IDL text
  toJSON(); // excludes `.parent` to prevent circular structure
  validate(); // `.tokens` includes position information so we can do line number thing here
};
```

**Comment by marcoscaceres** [comment]
The self-contained class structure seems pretty nice. Will make things more self contained.

**Comment by saschanaz** [comment]
Version 18 now supports `webidl2.validate(webidl2.parse(text))`. It only includes minimal features yet (for https://github.com/KhronosGroup/WebGL/issues/2216), feel free to open issues to request validations you need.

**Comment by kenrussell** [comment]
Thanks, that's great news!
