### ISSUE TITLE
Reduce release size

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#152]
We currently creates npm release with all those test files and test/widlproc submodule, probably we should add .npmignore (or `files` field on package.json) to remove them from npm.

I currently have no idea what test/widlproc is for, though.

**Comment by marcoscaceres** [comment]
widlproc used to be an old IDL processor, IIRC. It's likely that this project shared some stuff with that project a long time ago. It's likely test/widlproc is just left over stuff from long ago. 

Looking at the history, there are only a few commits from 2012. I think we should just delete all that.

**Comment by marcoscaceres** [comment]
https://github.com/w3c/webidl2.js/pull/9  was were it come from.  I wonder if @tobie remembers. 

In any case, those IDL files are going to be out of date now.

**Comment by tobie** [comment]
Nope. That predates my involvement with the project. Only @darobin might know.

**Comment by marcoscaceres** [comment]
Works ok removing them, so 🤷🏽‍♂️😎.
