### ISSUE TITLE
Request: tag releases

### ISSUE THREAD

**Issue by foolip** [w3c/webidl2.js#159]
The latest tagged release was v10.2.1, commit dd57b9f0db1adbb5712f9fdd6a4e38533ff4ba4b.

web-platform-tests rolls in webidl2.js, and has so far referred to a tag name when doing so. We can just roll in the develop branch, but given the "chore(package): bump version number" commits I wonder if they could be tagged. The tagged commit isn't always the same one which updates the version number.

**Comment by saschanaz** [comment]
Oooops, I forgot doing `git push --follow-tags`! I pushed all missing tags, thanks!

**Comment by marcoscaceres** [comment]
Maybe we should make a little release script?
