### ISSUE TITLE
Use ESLint (with Travis)

### ISSUE THREAD

**Issue by csnardi** [w3c/webidl2.js#167]
While pulling in new versions of webidl2.js to web platform tests and users of web platform tests (Chromium), I've noticed lines with trailing whitespace from time to time. Perhaps ESLint should be included 
and used so this doesn't occur?

**Comment by saschanaz** [comment]
Yes... I think we need it, as we sometimes also notice unused variables.

**Comment by marcoscaceres** [comment]
Running prettier would be good.

**Comment by saschanaz** [comment]
Closed by #202
