### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#215]
@marcoscaceres, what tool is currently used for changelog generation? I tried [`conventional-changelog`](https://www.npmjs.com/package/conventional-changelog-cli
) and 1) it seems the format is slightly different 2) it ignores the top header `# Change Log`.

**Comment by marcoscaceres** [comment]
I’ve been using https://github.com/github-changelog-generator/github-changelog-generator

**Comment by saschanaz** [comment]
1582972c217ca82c77156f50456dca9790d4f2f7 updates it 👍
