### ISSUE TITLE
Docs: Trivia object not well defined

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#225]
Was trying to work with the trivia object, but it's not very well defined at the moment. It's unclear, for instance, with `termination` if trivia comes before or after the `;`. 

Would also be nice to link mentions of "Trivia object" in the README to the Trivia section.

**Comment by saschanaz** [comment]
@marcoscaceres I think we can just remove the trivia field now. Originally it was designed to augment existing object types with minimal breaking changes while keeping JSON output human readable, but now have a replacement named `tokens`.

**Comment by marcoscaceres** [comment]
sure, whatever you think is best.

**Comment by saschanaz** [comment]
Became irrelevant by #306
