### ISSUE TITLE
Some leading underscores are no longer removed

### ISSUE THREAD

**Issue by TimothyGu** [w3c/webidl2.js#228]
Web IDL spec says:

> For all of these constructs [[named definitions](https://heycam.github.io/webidl/#dfn-named-definition), attributes, typedefs, dictionary members, constants, and operations], the [identifier](https://heycam.github.io/webidl/#dfn-identifier) is the value of the [**identifier**](https://heycam.github.io/webidl/#prod-identifier) token with any leading U+005F LOW LINE ("\_") character (underscore) removed.

However, webidl2.js no longer seems to remove some underscores, from identifiers that did not need them to start with:

```js
> require('webidl2').parse('interface _Int {};')
[ { type: 'interface',
    name: '_Int',
    partial: null,
    members: [],
    trivia:
     { base: '', name: ' ', open: ' ', close: '', termination: '' },
    inheritance: null,
    extAttrs: null },
  { type: 'eof', trivia: '' } ]
```

**Comment by saschanaz** [comment]
May I ask why `_Int` when we can just use `Int`?

**Comment by TimothyGu** [comment]
> May I ask why `_Int` when we can just use `Int`?

No reason. It just happened to be in one of our tests.
