### ISSUE TITLE
Point GitHub Pages at the master branch so the checker can be used online

### ISSUE THREAD

**Issue by kainino0x** [w3c/webidl2.js#259]
In #146, a checker was added so that `webidl2.js` can be used easily in a browser.
In order to make this more accessible, I think it would be nice to point the repository's GitHub Pages url at the master branch of this repository. That would make https://w3c.github.io/webidl2.js/checker/ point to the right page. (It would be nice to link the checker from the README, too.)

I did the same thing here, and it works great: https://kai.graphics/webidl2.js/checker/

**Comment by kainino0x** [comment]
Oh, I just realized that this doesn't work because webidl2.js has a `develop` branch instead of a `master` branch. In that case, a `gh-pages` branch could be added to make the GitHub Pages page work - which is *actually* what I did in my version. (But it wouldn't stay up-to-date automatically.)

**Comment by saschanaz** [comment]
Maybe we can just replace `develop` with `master`. Thoughts? @marcoscaceres

**Comment by marcoscaceres** [comment]
Historically, it was a political choice to not use `master`. To side-step this issue, let's do what @kainino0x suggests: let's add a `gh-pages` and make it the default branch (develop can then go away).

**Comment by saschanaz** [comment]
Okay, just did it. Check out https://w3c.github.io/webidl2.js/checker/ 👍

**Comment by marcoscaceres** [comment]
Looks good... unsure if we should just kill the develop branch and then just deal with any fallout. I think it should be fine, as the actual distribution channel for this is NPM - and not really GitHub.

**Comment by saschanaz** [comment]
Distribution through GitHub should not be broken as users are not expected to explicitly reference `develop` branch. Doing so can break in any time.

**Comment by saschanaz** [comment]
BTW I just found that our checker does not work as expected in Firefox because of a weird Firefox bug: `textarea.innerText` inserts `<br>` instead of newlines 🤔

**Comment by saschanaz** [comment]
Looks like my Chrome was not up to date? Just got Chrome 72 and now it shows same behavior as Firefox, which means: Our checker is broken in both browsers 🤣

**Comment by marcoscaceres** [comment]
Should we instead just set the `.value`?

**Comment by kainino0x** [comment]
`.value` seems like the right fix to me.

**Comment by marcoscaceres** [comment]
We went with `.innerText`.

**Comment by saschanaz** [comment]
I think we just selected `.textContent`.

**Comment by saschanaz** [comment]
I added https://w3c.github.io/webidl2.js/checker/ to the project description:

![image](https://user-images.githubusercontent.com/3396686/52098205-6908e180-2611-11e9-988a-feeb0ad058b2.png)

All good now?

**Comment by marcoscaceres** [comment]
All good from me. 

@kainino0x? Ok to close or anything to add?

**Comment by kainino0x** [comment]
Nothing to add. Thanks so much!
