### ISSUE TITLE
Is this the reference parser implementation for the latest webidl spec?

### ISSUE THREAD

**Issue by bglgwyng** [w3c/webidl2.js#316]
The attached file is webidl source from https://github.com/gpuweb/gpuweb.
But it failed to parse that.
I'm very noob in webidl, so I don't even know that the source is valid or this repo is not supporting the lastest syntax yet.
[webgpu.idl.txt](https://github.com/w3c/webidl2.js/files/3132363/webgpu.idl.txt)

**Comment by marcoscaceres** [comment]
Yes.

**Comment by bglgwyng** [comment]
@marcoscaceres sorry, I submitted the incomplete issue by mistake. Please re read what I asked.

**Comment by bglgwyng** [comment]
This is the partial source code the error occured.
```webidl
dictionary GPUColorStateDescriptor {
    required GPUTextureFormat format;

    required GPUBlendDescriptor alphaBlend;
    required GPUBlendDescriptor colorBlend;
    GPUColorWriteFlags writeMask = GPUColorWriteBits.ALL;
};
```
The error message is
> 
WebIDLParseError: Syntax error at line 381, since `undefined undefined`:
    GPUColorWriteFlags writeMask = GPUColorWriteBits.ALL;

**Comment by marcoscaceres** [comment]
Ah, that’s not currently allowed (it’s being discussed in the WebIDL repo):

GPUColorWriteFlags writeMask = GPUColorWriteBits.ALL;

You need to do:
GPUColorWriteFlags writeMask = 15;

For now.

**Comment by marcoscaceres** [comment]
Here is the IDL issue: https://github.com/heycam/webidl/issues/717

**Comment by marcoscaceres** [comment]
Closing as answered. If the WebIDL folks decide to add the new syntax, we will definitely support it.
