### ISSUE TITLE
Hard to upgrade to the latest version

### ISSUE THREAD

**Issue by TimothyGu** [w3c/webidl2.js#328]
The documentation refers to `extAttrs` as "An array of extended attributes." However, since around ten major releases ago it has become

```json
    "extAttrs": {
      "trivia": {
        "open": "",
        "close": ""
      },
      "items": [
        {
          "name": "A",
          "signature": null,
          "type": "extended-attribute",
          "rhs": {
            "type": "identifier",
            "value": "B",
            "trivia": {
              "assign": "",
              "value": ""
            }
          },
          "trivia": {
            "name": ""
          },
          "separator": null
        }
      ]
    }
```

----

In general, these `trivia` things do not really belong in an AST – they are the job of a CST. And having to adapt my code that has conformed to the previously very stable AST so that it accounts for these `trivia` properties is actually quite painful. The pace of major releases that have been happening recently – 10 to 21 in little more than a year – makes my job as a downstream user (who is not getting paid for doing these things) unbelievably difficult.

I'd like to ask that a stable AST format be adopted – perhaps frozen. I really think the number of breaking changes can be drastically reduced with a more careful approach at implementing features, and I hope you all consider this.

**Comment by TimothyGu** [comment]
I just discovered that #324, published in version 21, restores it as an array. However we cannot move past 14 until jsdom removes all `implements` statements… (there are 38 of them)

**Comment by marcoscaceres** [comment]
We have a number of different consumers with different requirements - we also don't get paid to maintain this project and we do the best we can with the limited resources we have. However, as much as we try, it's the nature of open source that things break (or we modernize our code, and always for good reason)... as I like to think of it, "you get what you pay for" :)

**Comment by saschanaz** [comment]
I think the syntax tree structure will be kept stable again. Sorry for the inconvenience.

BTW, are you maintaining webidl2js? I tried updating to webidl2.js@13 there and got blocked by https://github.com/jsdom/webidl2js/issues/117#issuecomment-446476689

**Comment by TimothyGu** [comment]
@marcoscaceres Yeah I definitely understand. Thanks for the explanation, but it's frustrating to see the AST change so drastically, so frequently. I definitely agree it's better that this is maintained at all than not ☺

@saschanaz Great to hear that! Yeah I am the maintainer of webidl2js, but I haven't been able to do much maintaining in the past few months. I've just put a PR that fixes that ☺ (https://github.com/jsdom/webidl2js/pull/125) Thanks a lot for discovering that issue.

**Comment by marcoscaceres** [comment]
@TimothyGu, we are happy to also help on the WPT side too (as I too depend heavily on WTP). We (maybe just me) are just a bit unsure where/how the code gets used over there.

**Comment by saschanaz** [comment]
Note that we have a WPT side PR https://github.com/web-platform-tests/wpt/pull/16864

**Comment by saschanaz** [comment]
I think the actionable item here is to remove `implements` from JSDOM, am I right? @TimothyGu

**Comment by TimothyGu** [comment]
@saschanaz I’ve done that already :)

**Comment by saschanaz** [comment]
@TimothyGu Great! Can this be closed in that case or is there other actionable thing?
