### ISSUE TITLE
Add quickfix feature?

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#349]
It can probably be doable as we got a writer feature, but some validation may need a proper context data e.g. from xref. Might be great for vast changes like https://github.com/heycam/webidl/issues/758.

**Comment by marcoscaceres** [comment]
Was thinking the same... that would be awesome, tbh.

**Comment by saschanaz** [comment]
The question would be about how to provide the context. I think maybe we just modify https://w3c.github.io/webidl2.js/checker/ to get multiple input boxes so that we can use one to provide some dictionary types...

**Comment by marcoscaceres** [comment]
I'm thinking for something like `eslint --fix` (but don't know now this translates). Something like heycam/webidl#758 is an obvious candidate.

**Comment by saschanaz** [comment]
A CLI command would be great but not sure it could be practically used, as IDLs are mostly embedded in other formats.

**Comment by marcoscaceres** [comment]
yeah, I guess I was thinking more in general terms... some kind of configuration flag/option to trigger the behavior.

**Comment by saschanaz** [comment]
Might still be able to create a linter feature that can parse HTML-like formats and automatically imports context data from xref. Sounds too great to dismiss 😋

**Comment by marcoscaceres** [comment]
Baby steps... just getting a warning up would be a good start.

**Comment by saschanaz** [comment]
One concern is... Parsing HTML will most definitely require a dependency, which will then most definitely make the dependency tree bloated 🤔

**Comment by saschanaz** [comment]
A simple regex or string search for `<pre></pre>`may work, though, as we don't need any other things.

**Comment by marcoscaceres** [comment]
why not just expect the calling program to pass the right  thing in... as we do  today? like...  `parse(idl,  {fix: true})`

**Comment by saschanaz** [comment]
That would be a building block. Fixing vast changes like https://github.com/heycam/webidl/issues/758 would require more automation, I wonder what would be best.

**Comment by marcoscaceres** [comment]
For heycam/webidl#758, we could deploy the autofix enabled by default on W3C specs. We could still warn  in ReSpec and ask Editors to republish their  specs  on TR.

**Comment by marcoscaceres** [comment]
(at  least  all the editor's drafts would be immediately  fixed. )

**Comment by saschanaz** [comment]
Okay, we should first enable out existing validator on ReSpec as that's a blocker of this. I think #347 would be required there to know which IDL block is problematic.

**Comment by marcoscaceres** [comment]
> I think #347 would be required there to know which IDL block is problematic.

We can use use the inline warning thing in ReSpec (via respec-offending-element), that will flag the right IDL block with red squiggles... that's a solid start at least at pointing to the problem.

**Comment by saschanaz** [comment]
The problem is we should collect the parser result and validate them in once, or otherwise we'll miss duplicated identifier check and dictionary type check. Flagging with red lines will be hard even after #347, maybe we'll have to return objects with `fileName` (or `blockName`? `snippetName`?) to flag the right blocke.

**Comment by marcoscaceres** [comment]
> The problem is we should collect the parser result and validate them in once, or otherwise we'll miss duplicated identifier check and dictionary type check.

True...  maybe we could do that check in the `idl-index` (if one is present)?... but  you are right that  we then need to backtrack to find where the offending definition came from. Alternatively, we collect all the `pre` IDL's into an array and send them into the validator. For duplicate interface names, I think it's ok to just complain without an exact position, as that rarely happens in a single document... doing the xref lookup is where it gets more interesting, but we could actually do that outside of WebIDL.js and do it as part of xref itself (as it's WebIDL aware).

**Comment by marcoscaceres** [comment]
There is also another service the w3c has called "Reffy"... which is also able to do then cross-document duplicate IDL check. https://github.com/w3c/respec/issues/1360

**Comment by saschanaz** [comment]
>True... maybe we could do that check in the idl-index (if one is present)?... but you are right that we then need to backtrack to find where the offending definition came from. Alternatively, we collect all the pre IDL's into an array and send them into the validator.

Collecting into an array is what I want to do in #347, but we still need some kind of identifier to properly backtrack them. Also consider a case that we have multiple files, like in WPT: it will be useful to get a correct filename. (I heard a voice that validation within WPT CI will be helpful not to downstream an improper IDL.)

>For duplicate interface names, I think it's ok to just complain without an exact position, as that rarely happens in a single document

You are right 😁

>doing the xref lookup is where it gets more interesting, but we could actually do that outside of WebIDL.js and do it as part of xref itself (as it's WebIDL aware).

**Comment by marcoscaceres** [comment]
> Also consider a case that we have multiple files, like in WPT: it will be useful to get a correct filename. (I have heard a voice that validation within WPT CI will be helpful not to downstream an improper IDL.)

yeah, that would be nice actually. But a CLI tool might be the way to go there. That could be outside the scope of what ReSpec does, and we could spin up a new project just for a webidl-cli.

**Comment by marcoscaceres** [comment]
Actually, cli would still depend on the library collecting the files... hmm... 🤔

**Comment by saschanaz** [comment]
Do you have a specific concern about adding a tracking identifier, that is, a filename?

**Comment by marcoscaceres** [comment]
Nope, no concerns from me.

**Comment by saschanaz** [comment]
Closed by #387
