### ISSUE TITLE
Validating Constructors as argument-types

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#363]
#359 is working well for catching method args that don't include `= {}`, but we seem to be missing this behaviour for `Constructor` extended attributes. 

Some examples:
https://github.com/w3c/payment-request/pull/874/files

**Comment by saschanaz** [comment]
Ah yes, it's not enabled for extattrs. I'll fix it.

When can we merge #300 BTW? 🤔

**Comment by marcoscaceres** [comment]
Unfortunately, heycam/webidl#700 hasn't landed yet... :(

**Comment by saschanaz** [comment]
That PR waits for WPT changes (AFAIK because any real spec changes before WPT support will break WPT), and WPT depends on webidl2.js... Hmm.

Browser implementations are independent anyway but not sure they are really interested.

**Comment by marcoscaceres** [comment]
oh, we could land it... and just not advertise it too spec editors.

**Comment by marcoscaceres** [comment]
Closed via  #364
