### ISSUE TITLE
In-browser tests from make-web-tests.js are broken

### ISSUE THREAD

**Issue by lukebjerring** [w3c/webidl2.js#366]
Following the instructions in the README doesn't work.
https://github.com/w3c/webidl2.js#browser-tests

I noticed
- The `syntax/idl` is gone (it's `syntax/baseline` now)
- The baselines are different assertions
- The src'd `lib/webidl2.js` is an es6 module, so can't load via a vanilla script tag

I fixed the above, but hit the more fundamental issue of how baselines are compared being wrong.

**Comment by saschanaz** [comment]
Oops, sorry for the inconvenience. We haven't maintained the browser tests for a while, do you have a specific use case in mind that `npm test` does not serve well?

**Comment by lukebjerring** [comment]
No; no reason that `npm test` isn't adequate. Maybe the "fix" here is a PR to simply delete the stale code/instructions?

**Comment by saschanaz** [comment]
@marcoscaceres Do you agree we can just remove the browser test?

**Comment by marcoscaceres** [comment]
Yeah, that seems fine.
