### ISSUE TITLE
Adding `[NoInterfaceObject]` must suppress `[Exposed]` requirement

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#370]
Found from https://github.com/WICG/media-playback-quality/issues/14

**Comment by marcoscaceres** [comment]
Oh, good point... additionally, we don't want `NoInterfaceObject`... it's an undesirable feature. I wonder if we should  start warning (not error).

**Comment by saschanaz** [comment]
Currently we don't have any notion of severity, maybe we can add one.

**Comment by marcoscaceres** [comment]
Yeah, would be good I  think.
