### ISSUE TITLE
Consider using GitHub Actions

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#373]
@marcoscaceres I tried adding NPM actions via [this page](https://github.com/marketplace/actions/github-action-for-npm) but it says we are not ready:

![image](https://user-images.githubusercontent.com/3396686/61505571-40876f00-aa1a-11e9-903d-bc012d961f5c.png)

Maybe an W3C member should explicitly join the public beta of GitHub Actions, so could you join from https://github.com/features/actions?

**Comment by marcoscaceres** [comment]
@sidvishnoi can probably guide us here. He's done some gh actions before.

**Comment by sidvishnoi** [comment]
@saschanaz is correct. Someone who's member of W3C need to join the public beta and enable GitHub Actions.

**Comment by marcoscaceres** [comment]
Ok, so no of us have enough power? @siusin maybe can help us?

**Comment by marcoscaceres** [comment]
Just to be clear, do they need need to be enabled at the org level?

**Comment by saschanaz** [comment]
@marcoscaceres Probably yes, as I didn't see anything about enabling for each repo.

**Comment by siusin** [comment]
Hi all, 

I've already informed our sys-team about this request. If there is no objection from them, I'll enable GitHub Actions on Friday. Apologise for the delay.

**Comment by marcoscaceres** [comment]
Thanks so much @siusin! That's great!

**Comment by siusin** [comment]
Still in the queue for the beta... will try to enable GitHub Actions once I gain access :)

**Comment by saschanaz** [comment]
Closed by #386 🎉
