### ISSUE TITLE
error parsing IDL files

### ISSUE THREAD

**Issue by am06** [w3c/webidl2.js#381]
Hi all,

I'm learning about IDL files and trying to parse some IDLs from firefox and chrome code. Couldn't find any from Chakra.

This file gives an error on parsing:
https://raw.githubusercontent.com/mozilla/gecko-dev/aaac9a77dd456360551dd764ffba4ca4899dcb56/widget/nsIClipboardHelper.idl

and it's not the only one. 

Many thanks,
A

**Comment by saschanaz** [comment]
Hi @am06!

That Mozilla IDL file uses Mozilla-specific IDL syntax `in` inside argument lists, which is not in standard Web IDL and not supported by this library.

Supporting vender-specific IDL syntax is currently out of scope of this library. Sorry 😥

**Comment by saschanaz** [comment]
BTW, I would go https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl and try parsing those files if you are only to study about IDL.

**Comment by am06** [comment]
Sorry, maybe I wasn't clear enough......I'm interested in parsing browser's IDL files.

Any idea how I could achieve that then if they're non-standard? Cheers!

**Comment by saschanaz** [comment]
reffy-reports IDL files *are* for browsers, each browser is just customizing them for their implementation.

If you still want to parse the customized files, you might fork this library and add support for the additional syntax.

**Comment by marcoscaceres** [comment]
closing, as this is not actionable for us.

**Comment by am06** [comment]
ps: and if i'd like to fork this library and add support for additional syntax how would I do that? some pointers please?

Thanks.
