### ISSUE TITLE
WebIDLParseError:  namespace  Missing return type

### ISSUE THREAD

**Issue by ihgazni2** [w3c/webidl2.js#390]
issue
------

    APZTestData
    WebIDLParseError: Syntax error at line 71, since `namespace APZHitResultFlags`:
      const unsigned short INVISIBLE =
      ^ Missing return type
        at l.error (/opt/JS/MDN/node_modules/webidl2/dist/webidl2.js:1:3920)
        at parse (/opt/JS/MDN/node_modules/webidl2/dist/webidl2.js:1:12556)
        at Function.parse (/opt/JS/MDN/node_modules/webidl2/dist/webidl2.js:1:19341)
        at Function.parse (/opt/JS/MDN/node_modules/webidl2/dist/webidl2.js:1:24185)
        at i (/opt/JS/MDN/node_modules/webidl2/dist/webidl2.js:1:25658)
    >

webidl file url
---------------

https://dxr.mozilla.org/mozilla-central/source/dom/webidl/APZTestData.webidl

error line 71
-------------

     65 [Pref="apz.test.logging_enabled"]
     66
     67 namespace APZHitResultFlags {
     68
     69   // These constants should be kept in sync with mozilla::gfx::CompositorHitTestInfo
     70
     71   const unsigned short INVISIBLE = 0;
     72
     73   const unsigned short VISIBLE = 0x0001;
     74

**Comment by saschanaz** [comment]
This is expected because [per the spec](https://heycam.github.io/webidl/#prod-NamespaceMember) namespaces does not support constants. I assume the APZ thing is using Mozilla specific extension. cc: @bzbarsky

**Comment by saschanaz** [comment]
Closing this, feel free to file a bug on https://bugzilla.mozilla.org/.

**Comment by bzbarsky** [comment]
See https://github.com/heycam/webidl/issues/440
