### ISSUE TITLE
Incorrect "Trailing comma in arguments list" when parsing HTML's IDL

### ISSUE THREAD

**Issue by foolip** [w3c/webidl2.js#402]
See https://github.com/web-platform-tests/wpt/pull/18722#issuecomment-526808403

I'm pretty sure this is a regression in webidl2.js, but I haven't minified the IDL snippet or bisected.

**Comment by saschanaz** [comment]
This is because `constructor` is not a valid identifier, it had been reserved and now is a keyword after https://github.com/heycam/webidl/pull/700.

Definitely not very helpful error message, though.

**Comment by foolip** [comment]
Is there a PR for HTML to fix this? And shouldn't it be allowed as an argument name, like `async`?

**Comment by saschanaz** [comment]
> Is there a PR for HTML to fix this? And shouldn't it be allowed as an argument name, like `async`?

We can't even escape as `_constructor` because it's reserved. Not sure we should keep it reserved though, @bzbarsky?

**Comment by bzbarsky** [comment]
See https://github.com/heycam/webidl/issues/779

**Comment by bzbarsky** [comment]
As far as keeping it reserved, we don't want people defining operations or attributes name `constructor`, even via the `_` escape, because that messes with normal JS semantics.

**Comment by foolip** [comment]
Are reserved keywords a single set in Web IDL, or could it be allowed as an argument name only? Calling the argument `ctor` would of course be trivial if that's not possible.

**Comment by bzbarsky** [comment]
The reserved identifier bit doesn't apply to things added via the ArgumentName production that are not identifiers, afaict.  Or it shouldn't, and if it does we should fix that; the point is that you don't want to define operations or attributes with that name is all.

**Comment by saschanaz** [comment]
Opened https://github.com/heycam/webidl/pull/786 to fix this.

**Comment by saschanaz** [comment]
Closed by #404
