### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by am06** [w3c/webidl2.js#408]
How do I actually run this and parse and IDL files with nodejs?

This is my first time working on a nodejs project.

thanks

**Comment by saschanaz** [comment]
Hi, a short code would be:

```js
const { parse } = require("webidl2");
parse("interface mixin Mixin {};");
```

**Comment by am06** [comment]
thanks @saschanaz , I was doing a very stupid mistake :(

I made some progress, but I get a parsing error when trying to parse a real IDL file from:
https://www.w3.org/TR/2dcontext/

```
typedef (HTMLImageElement or
         HTMLVideoElement or
         HTMLCanvasElement) CanvasImageSource;

interface CanvasRenderingContext2D {

  // back-reference to the canvas
  readonly attribute HTMLCanvasElement canvas;

  // state
  void save(); // push state on state stack
  void restore(); // pop state stack and restore state

  // transformations (default: transform is the identity matrix)
  void scale(unrestricted double x, unrestricted double y);
  void rotate(unrestricted double angle);
  void translate(unrestricted double x, unrestricted double y);
  void transform(unrestricted double a, unrestricted double b, unrestricted double c, unrestricted double d, unrestricted double e, unrestricted double f);
  void setTransform(unrestricted double a, unrestricted double b, unrestricted double c, unrestricted double d, unrestricted double e, unrestricted double f);

  // compositing
           attribute unrestricted double globalAlpha; // (default: 1.0)
           attribute DOMString globalCompositeOperation; // (default: "source-over")

  // colors and styles (see also the CanvasDrawingStyles interface)
           attribute (DOMString or CanvasGradient or CanvasPattern) strokeStyle; // (default: "black")
           attribute (DOMString or CanvasGradient or CanvasPattern) fillStyle; // (default: "black")
  CanvasGradient createLinearGradient(double x0, double y0, double x1, double y1);
  CanvasGradient createRadialGradient(double x0, double y0, double r0, double x1, double y1, double r1);
  CanvasPattern createPattern(CanvasImageSource image, [TreatNullAs=EmptyString] DOMString repetition);

  // shadows
           attribute unrestricted double shadowOffsetX; // (default: 0)
           attribute unrestricted double shadowOffsetY; // (default: 0)
           attribute unrestricted double shadowBlur; // (default: 0)
           attribute DOMString shadowColor; // (default: "transparent black")

  // rects
  void clearRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
  void fillRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
  void strokeRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);

  // path API (see also CanvasPathMethods)
  void beginPath();
  void fill();
  void stroke();
  void drawFocusIfNeeded(Element element);
  void clip();
  boolean isPointInPath(unrestricted double x, unrestricted double y);

  // text (see also the CanvasDrawingStyles interface)
  void fillText(DOMString text, unrestricted double x, unrestricted double y, optional unrestricted double maxWidth);
  void strokeText(DOMString text, unrestricted double x, unrestricted double y, optional unrestricted double maxWidth);
  TextMetrics measureText(DOMString text);

  // drawing images
  void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy);
  void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);
  void drawImage(CanvasImageSource image, unrestricted double sx, unrestricted double sy, unrestricted double sw, unrestricted double sh, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);

  // hit regions
  void addHitRegion(HitRegionOptions options);
  void removeHitRegion(DOMString id);
  void clearHitRegions();

  // pixel manipulation
  ImageData createImageData(unrestricted double sw, unrestricted double sh);
  ImageData createImageData(ImageData imagedata);
  ImageData getImageData(double sx, double sy, double sw, double sh);
  void putImageData(ImageData imagedata, double dx, double dy);
  void putImageData(ImageData imagedata, double dx, double dy, double dirtyX, double dirtyY, double dirtyWidth, double dirtyHeight);
};
CanvasRenderingContext2D implements CanvasDrawingStyles;
CanvasRenderingContext2D implements CanvasPathMethods;

[NoInterfaceObject]
interface CanvasDrawingStyles {
  // line caps/joins
           attribute unrestricted double lineWidth; // (default: 1)
           attribute DOMString lineCap; // "butt", "round", "square" (default: "butt")
           attribute DOMString lineJoin; // "round", "bevel", "miter" (default: "miter")
           attribute unrestricted double miterLimit; // (default: 10)

  // dashed lines
  void setLineDash(sequence<unrestricted double> segments); // (default: empty)
  sequence<unrestricted double> getLineDash();
           attribute unrestricted double lineDashOffset;


  // text
           attribute DOMString font; // (default: "10px sans-serif")
           attribute DOMString textAlign; // "start", "end", "left", "right", "center" (default: "start")
           attribute DOMString textBaseline; // "top", "hanging", "middle", "alphabetic", "ideographic", "bottom" (default: "alphabetic")
};

[NoInterfaceObject]
interface CanvasPathMethods {
  // shared path API methods
  void closePath();
  void moveTo(unrestricted double x, unrestricted double y);
  void lineTo(unrestricted double x, unrestricted double y);
  void quadraticCurveTo(unrestricted double cpx, unrestricted double cpy, unrestricted double x, unrestricted double y);
  void bezierCurveTo(unrestricted double cp1x, unrestricted double cp1y, unrestricted double cp2x, unrestricted double cp2y, unrestricted double x, unrestricted double y);
  void arcTo(unrestricted double x1, unrestricted double y1, unrestricted double x2, unrestricted double y2, unrestricted double radius); 
  void rect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
  void arc(unrestricted double x, unrestricted double y, unrestricted double radius, unrestricted double startAngle, unrestricted double endAngle, optional boolean counterclockwise = false); 

  };

interface CanvasGradient {
  // opaque object
  void addColorStop(double offset, DOMString color);
};

interface CanvasPattern {
  // opaque object
};

interface TextMetrics {
  readonly attribute double width;
};

dictionary HitRegionOptions {
  // dictionary to allow expansion on Hit Regions in Canvas Context 2D Level 2
  DOMString id = "";
  // for control-backed regions:
  Element? control = null;
};

interface ImageData {
  readonly attribute unsigned long width;
  readonly attribute unsigned long height;
  readonly attribute Uint8ClampedArray data;
};
```

I've removed the \r\n sequences, I noticed it doesn't like them and then I got this error:

`     ^ Missing return type
    at W.error (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:16246)
    at parse (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:10168)
    at Function.parse (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:19734)
    at Function.parse (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:22505)
    at o (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:26831)
    at i (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:26996)
    at c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:27292
    at te (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:27421)
    at ne (c:\Users\Adrian\Documents\GitHub\webidl\dist\webidl2.js:1:27575)
    at Object.<anonymous> (c:\Users\Adrian\Documents\GitHub\webidl\parse.js:140:14)`

**Comment by saschanaz** [comment]
That IDL is 4 years old and now incompatible with the latest IDL syntax. Try the latest one: https://html.spec.whatwg.org/multipage/canvas.html#2dcontext

**Comment by am06** [comment]
I get the same error .......

how can I make sure I always use the latest idl?

**Comment by saschanaz** [comment]
> how can I make sure I always use the latest idl?

Prefer using Editor's Drafts over snapshots (which includes `/TR/` in their URL), as drafts are frequently updated to match the latest syntax.

Weird that you are still getting errors, which webidl2 version are you using?

**Comment by am06** [comment]
thanks for the tip.

latest, I jusd ran a git pull

**Comment by am06** [comment]
does it work for you? can you share your code please?

**Comment by saschanaz** [comment]
I already gave you the code, it should just work.

**Comment by saschanaz** [comment]
I'm not sure what version you are using. By `git pull` did you mean you are using local clone of this repo?

**Comment by am06** [comment]
yes local clone of this repo.

im using 169d78d3960a722364a8f763c6545e1a73984771

**Comment by saschanaz** [comment]
You'll typically start with an empty directory and `npm init && npm install webidl2@latest` when you start a new Node.js project.

If things still don't work, please try my suggestion.

**Comment by am06** [comment]
same thing :(

**Comment by saschanaz** [comment]
Could you repeat your input and the error message?

**Comment by am06** [comment]
code is this:

`const process = require('process');
const { parse, write, validate } = require("webidl2");

var idl=`typedef (HTMLImageElement or
         SVGImageElement) HTMLOrSVGImageElement;

typedef (HTMLOrSVGImageElement or
         HTMLVideoElement or
         HTMLCanvasElement or
         ImageBitmap or
         OffscreenCanvas) CanvasImageSource;

enum CanvasFillRule { "nonzero", "evenodd" };

dictionary CanvasRenderingContext2DSettings {
  boolean alpha = true;
  boolean desynchronized = false;
};

enum ImageSmoothingQuality { "low", "medium", "high" };

[Exposed=Window]
interface CanvasRenderingContext2D {
  // back-reference to the canvas
  readonly attribute HTMLCanvasElement canvas;

  CanvasRenderingContext2DSettings getContextAttributes();
};
CanvasRenderingContext2D includes CanvasState;
CanvasRenderingContext2D includes CanvasTransform;
CanvasRenderingContext2D includes CanvasCompositing;
CanvasRenderingContext2D includes CanvasImageSmoothing;
CanvasRenderingContext2D includes CanvasFillStrokeStyles;
CanvasRenderingContext2D includes CanvasShadowStyles;
CanvasRenderingContext2D includes CanvasFilters;
CanvasRenderingContext2D includes CanvasRect;
CanvasRenderingContext2D includes CanvasDrawPath;
CanvasRenderingContext2D includes CanvasUserInterface;
CanvasRenderingContext2D includes CanvasText;
CanvasRenderingContext2D includes CanvasDrawImage;
CanvasRenderingContext2D includes CanvasImageData;
CanvasRenderingContext2D includes CanvasPathDrawingStyles;
CanvasRenderingContext2D includes CanvasTextDrawingStyles;
CanvasRenderingContext2D includes CanvasPath;

interface mixin CanvasState {
  // state
  void save(); // push state on state stack
  void restore(); // pop state stack and restore state
};

interface mixin CanvasTransform {
  // transformations (default transform is the identity matrix)
  void scale(unrestricted double x, unrestricted double y);
  void rotate(unrestricted double angle);
  void translate(unrestricted double x, unrestricted double y);
  void transform(unrestricted double a, unrestricted double b, unrestricted double c, unrestricted double d, unrestricted double e, unrestricted double f);

  [NewObject] DOMMatrix getTransform();
  void setTransform(unrestricted double a, unrestricted double b, unrestricted double c, unrestricted double d, unrestricted double e, unrestricted double f);
  void setTransform(optional DOMMatrix2DInit transform = {});
  void resetTransform();

};

interface mixin CanvasCompositing {
  // compositing
  attribute unrestricted double globalAlpha; // (default 1.0)
  attribute DOMString globalCompositeOperation; // (default source-over)
};

interface mixin CanvasImageSmoothing {
  // image smoothing
  attribute boolean imageSmoothingEnabled; // (default true)
  attribute ImageSmoothingQuality imageSmoothingQuality; // (default low)

};

interface mixin CanvasFillStrokeStyles {
  // colors and styles (see also the CanvasPathDrawingStyles and CanvasTextDrawingStyles interfaces)
  attribute (DOMString or CanvasGradient or CanvasPattern) strokeStyle; // (default black)
  attribute (DOMString or CanvasGradient or CanvasPattern) fillStyle; // (default black)
  CanvasGradient createLinearGradient(double x0, double y0, double x1, double y1);
  CanvasGradient createRadialGradient(double x0, double y0, double r0, double x1, double y1, double r1);
  CanvasPattern? createPattern(CanvasImageSource image, [TreatNullAs=EmptyString] DOMString repetition);

};

interface mixin CanvasShadowStyles {
  // shadows
  attribute unrestricted double shadowOffsetX; // (default 0)
  attribute unrestricted double shadowOffsetY; // (default 0)
  attribute unrestricted double shadowBlur; // (default 0)
  attribute DOMString shadowColor; // (default transparent black)
};

interface mixin CanvasFilters {
  // filters
  attribute DOMString filter; // (default "none")
};

interface mixin CanvasRect {
  // rects
  void clearRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
  void fillRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
  void strokeRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
};

interface mixin CanvasDrawPath {
  // path API (see also CanvasPath)
  void beginPath();
  void fill(optional CanvasFillRule fillRule = "nonzero");
  void fill(Path2D path, optional CanvasFillRule fillRule = "nonzero");
  void stroke();
  void stroke(Path2D path);
  void clip(optional CanvasFillRule fillRule = "nonzero");
  void clip(Path2D path, optional CanvasFillRule fillRule = "nonzero");
  boolean isPointInPath(unrestricted double x, unrestricted double y, optional CanvasFillRule fillRule = "nonzero");
  boolean isPointInPath(Path2D path, unrestricted double x, unrestricted double y, optional CanvasFillRule fillRule = "nonzero");
  boolean isPointInStroke(unrestricted double x, unrestricted double y);
  boolean isPointInStroke(Path2D path, unrestricted double x, unrestricted double y);
};

interface mixin CanvasUserInterface {
  void drawFocusIfNeeded(Element element);
  void drawFocusIfNeeded(Path2D path, Element element);
  void scrollPathIntoView();
  void scrollPathIntoView(Path2D path);
};

interface mixin CanvasText {
  // text (see also the CanvasPathDrawingStyles and CanvasTextDrawingStyles interfaces)
  void fillText(DOMString text, unrestricted double x, unrestricted double y, optional unrestricted double maxWidth);
  void strokeText(DOMString text, unrestricted double x, unrestricted double y, optional unrestricted double maxWidth);
  TextMetrics measureText(DOMString text);
};

interface mixin CanvasDrawImage {
  // drawing images
  void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy);
  void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);
  void drawImage(CanvasImageSource image, unrestricted double sx, unrestricted double sy, unrestricted double sw, unrestricted double sh, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);
};

interface mixin CanvasImageData {
  // pixel manipulation
  ImageData createImageData(long sw, long sh);
  ImageData createImageData(ImageData imagedata);
  ImageData getImageData(long sx, long sy, long sw, long sh);
  void putImageData(ImageData imagedata, long dx, long dy);
  void putImageData(ImageData imagedata, long dx, long dy, long dirtyX, long dirtyY, long dirtyWidth, long dirtyHeight);
};

enum CanvasLineCap { "butt", "round", "square" };
enum CanvasLineJoin { "round", "bevel", "miter" };
enum CanvasTextAlign { "start", "end", "left", "right", "center" };
enum CanvasTextBaseline { "top", "hanging", "middle", "alphabetic", "ideographic", "bottom" };
enum CanvasDirection { "ltr", "rtl", "inherit" };

interface mixin CanvasPathDrawingStyles {
  // line caps/joins
  attribute unrestricted double lineWidth; // (default 1)
  attribute CanvasLineCap lineCap; // (default "butt")
  attribute CanvasLineJoin lineJoin; // (default "miter")
  attribute unrestricted double miterLimit; // (default 10)

  // dashed lines
  void setLineDash(sequence<unrestricted double> segments); // default empty
  sequence<unrestricted double> getLineDash();
  attribute unrestricted double lineDashOffset;
};

interface mixin CanvasTextDrawingStyles {
  // text
  attribute DOMString font; // (default 10px sans-serif)
  attribute CanvasTextAlign textAlign; // (default: "start")
  attribute CanvasTextBaseline textBaseline; // (default: "alphabetic")
  attribute CanvasDirection direction; // (default: "inherit")
};

interface mixin CanvasPath {
  // shared path API methods
  void closePath();
  void moveTo(unrestricted double x, unrestricted double y);
  void lineTo(unrestricted double x, unrestricted double y);
  void quadraticCurveTo(unrestricted double cpx, unrestricted double cpy, unrestricted double x, unrestricted double y);
  void bezierCurveTo(unrestricted double cp1x, unrestricted double cp1y, unrestricted double cp2x, unrestricted double cp2y, unrestricted double x, unrestricted double y);
  void arcTo(unrestricted double x1, unrestricted double y1, unrestricted double x2, unrestricted double y2, unrestricted double radius);
  void rect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);
  void arc(unrestricted double x, unrestricted double y, unrestricted double radius, unrestricted double startAngle, unrestricted double endAngle, optional boolean anticlockwise = false);
  void ellipse(unrestricted double x, unrestricted double y, unrestricted double radiusX, unrestricted double radiusY, unrestricted double rotation, unrestricted double startAngle, unrestricted double endAngle, optional boolean anticlockwise = false);
};

[Exposed=(Window,Worker)]
interface CanvasGradient {
  // opaque object
  void addColorStop(double offset, DOMString color);
};

[Exposed=(Window,Worker)]
interface CanvasPattern {
  // opaque object
  void setTransform(optional DOMMatrix2DInit transform = {});
};

[Exposed=(Window,Worker)]
interface TextMetrics {
  // x-direction
  readonly attribute double width; // advance width
  readonly attribute double actualBoundingBoxLeft;
  readonly attribute double actualBoundingBoxRight;

  // y-direction
  readonly attribute double fontBoundingBoxAscent;
  readonly attribute double fontBoundingBoxDescent;
  readonly attribute double actualBoundingBoxAscent;
  readonly attribute double actualBoundingBoxDescent;
  readonly attribute double emHeightAscent;
  readonly attribute double emHeightDescent;
  readonly attribute double hangingBaseline;
  readonly attribute double alphabeticBaseline;
  readonly attribute double ideographicBaseline;
};

[Constructor(unsigned long sw, unsigned long sh),
 Constructor(Uint8ClampedArray data, unsigned long sw, optional unsigned long sh),
 Exposed=(Window,Worker),
 Serializable]
interface ImageData {
  readonly attribute unsigned long width;
  readonly attribute unsigned long height;
  readonly attribute Uint8ClampedArray data;
};

[Constructor(optional (Path2D or DOMString) path),
 Exposed=(Window,Worker)]
interface Path2D {
  void addPath(Path2D path, optional DOMMatrix2DInit transform = {});
};
Path2D includes CanvasPath;`.replace(/\r?\n|\r/g, " ");
//process.exit(1);
const tree = parse(idl);
console.log(tree);
const text = write(tree);
//write(text);
console.log("Write \n" + text);
const validation = validate(tree);
console.log("Validation \n" + validation);
`

error is this:

`>node parse.js
c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.WebIDL2=t():e.WebIDL2=t()}(this,function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var s=t[r]={i:r,l:!1,exports:{}};return e[r].call(s.exports,s,s.exports,n),s.l=!0,s.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var s in e)n.d(r,s,function(t){return e[t]}.bind(null,s));return r},n.n=fun

WebIDLParseError: Syntax error at line 1, since `interface CanvasRenderingContext2D`:
Window] interface CanvasRenderingContext2D {   // back-reference to the canvas   readonly attribute HTMLCanvasElement canvas;    CanvasRenderingContext2DSettings getContextAttributes(); }; CanvasRenderingContext2D includes CanvasState; CanvasRenderingContext2D includes CanvasTransform; CanvasRenderingContext2D includes CanvasCompositing; CanvasRenderingContext2D includes CanvasImageSmoothing; CanvasRenderingContext2D includes CanvasFillStrokeStyles; CanvasRenderingContext2D includes CanvasShadowStyles; CanvasRenderingContext2D includes CanvasFilters; CanvasRenderingContext2D includes CanvasRect; CanvasRenderingContext2D includes CanvasDrawPath; CanvasRenderingContext2D includes CanvasUserInterface; CanvasRenderingContext2D includes CanvasText; CanvasRenderingContext2D includes CanvasDrawImage; CanvasRenderingContext2D includes CanvasImageData; CanvasRenderingContext2D includes CanvasPathDrawingStyles; CanvasRenderingContext2D includes CanvasTextDrawingStyles; CanvasRenderingContext2D includes CanvasPath;  interface mixin CanvasState {   // state   void save(); // push state on state stack   void restore(); // pop state stack and restore state };  interface mixin CanvasTransform {   // transformations (default transform is the identity matrix)   void scale(unrestricted double x, unrestricted double y);   void rotate(unrestricted double angle);   void translate(unrestricted double x, unrestricted double y);   void transform(unrestricted double a, unrestricted double b, unrestricted double c, unrestricted double d, unrestricted double e, unrestricted double f);    [NewObject] DOMMatrix getTransform();   void setTransform(unrestricted double a, unrestricted double b, unrestricted double c, unrestricted double d, unrestricted double e, unrestricted double f);   void setTransform(optional DOMMatrix2DInit transform = {});   void resetTransform();  };  interface mixin CanvasCompositing {   // compositing   attribute unrestricted double globalAlpha; // (default 1.0)   attribute DOMString globalCompositeOperation; // (default source-over) };  interface mixin CanvasImageSmoothing {   // image smoothing   attribute boolean imageSmoothingEnabled; // (default true)   attribute ImageSmoothingQuality imageSmoothingQuality; // (default low)  };  interface mixin CanvasFillStrokeStyles {   // colors and styles (see also the CanvasPathDrawingStyles and CanvasTextDrawingStyles interfaces)   attribute (DOMString or CanvasGradient or CanvasPattern) strokeStyle; // (default black)   attribute (DOMString or CanvasGradient or CanvasPattern) fillStyle; // (default black)   CanvasGradient createLinearGradient(double x0, double y0, double x1, double y1);   CanvasGradient createRadialGradient(double x0, double y0, double r0, double x1, double y1, double r1);   CanvasPattern? createPattern(CanvasImageSource image, [TreatNullAs=EmptyString] DOMString repetition);  };  interface mixin CanvasShadowStyles {   // shadows   attribute unrestricted double shadowOffsetX; // (default 0)   attribute unrestricted double shadowOffsetY; // (default 0)   attribute unrestricted double shadowBlur; // (default 0)   attribute DOMString shadowColor; // (default transparent black) };  interface mixin CanvasFilters {   // filters   attribute DOMString filter; // (default "none") };  interface mixin CanvasRect {   // rects   void clearRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);   void fillRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);   void strokeRect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h); };  interface mixin CanvasDrawPath {   // path API (see also CanvasPath)   void beginPath();   void fill(optional CanvasFillRule fillRule = "nonzero");   void fill(Path2D path, optional CanvasFillRule fillRule = "nonzero");   void stroke();   void stroke(Path2D path);   void clip(optional CanvasFillRule fillRule = "nonzero");   void clip(Path2D path, optional CanvasFillRule fillRule = "nonzero");   boolean isPointInPath(unrestricted double x, unrestricted double y, optional CanvasFillRule fillRule = "nonzero");   boolean isPointInPath(Path2D path, unrestricted double x, unrestricted double y, optional CanvasFillRule fillRule = "nonzero");   boolean isPointInStroke(unrestricted double x, unrestricted double y);   boolean isPointInStroke(Path2D path, unrestricted double x, unrestricted double y); };  interface mixin CanvasUserInterface {   void drawFocusIfNeeded(Element element);   void drawFocusIfNeeded(Path2D path, Element element);   void scrollPathIntoView();   void scrollPathIntoView(Path2D path); };  interface mixin CanvasText {   // text (see also the CanvasPathDrawingStyles and CanvasTextDrawingStyles interfaces)   void fillText(DOMString text, unrestricted double x, unrestricted double y, optional unrestricted double maxWidth);   void strokeText(DOMString text, unrestricted double x, unrestricted double y, optional unrestricted double maxWidth);   TextMetrics measureText(DOMString text); };  interface mixin CanvasDrawImage {   // drawing images   void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy);   void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);   void drawImage(CanvasImageSource image, unrestricted double sx, unrestricted double sy, unrestricted double sw, unrestricted double sh, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh); };  interface mixin CanvasImageData {   // pixel manipulation   ImageData createImageData(long sw, long sh);   ImageData createImageData(ImageData imagedata);   ImageData getImageData(long sx, long sy, long sw, long sh);   void putImageData(ImageData imagedata, long dx, long dy);   void putImageData(ImageData imagedata, long dx, long dy, long dirtyX, long dirtyY, long dirtyWidth, long dirtyHeight); };  enum CanvasLineCap { "butt", "round", "square" }; enum CanvasLineJoin { "round", "bevel", "miter" }; enum CanvasTextAlign { "start", "end", "left", "right", "center" }; enum CanvasTextBaseline { "top", "hanging", "middle", "alphabetic", "ideographic", "bottom" }; enum CanvasDirection { "ltr", "rtl", "inherit" };  interface mixin CanvasPathDrawingStyles {   // line caps/joins   attribute unrestricted double lineWidth; // (default 1)   attribute CanvasLineCap lineCap; // (default "butt")   attribute CanvasLineJoin lineJoin; // (default "miter")   attribute unrestricted double miterLimit; // (default 10)    // dashed lines   void setLineDash(sequence<unrestricted double> segments); // default empty   sequence<unrestricted double> getLineDash();   attribute unrestricted double lineDashOffset; };  interface mixin CanvasTextDrawingStyles {   // text   attribute DOMString font; // (default 10px sans-serif)   attribute CanvasTextAlign textAlign; // (default: "start")   attribute CanvasTextBaseline textBaseline; // (default: "alphabetic")   attribute CanvasDirection direction; // (default: "inherit") };  interface mixin CanvasPath {   // shared path API methods   void closePath();   void moveTo(unrestricted double x, unrestricted double y);   void lineTo(unrestricted double x, unrestricted double y);   void quadraticCurveTo(unrestricted double cpx, unrestricted double cpy, unrestricted double x, unrestricted double y);   void bezierCurveTo(unrestricted double cp1x, unrestricted double cp1y, unrestricted double cp2x, unrestricted double cp2y, unrestricted double x, unrestricted double y);   void arcTo(unrestricted double x1, unrestricted double y1, unrestricted double x2, unrestricted double y2, unrestricted double radius);   void rect(unrestricted double x, unrestricted double y, unrestricted double w, unrestricted double h);   void arc(unrestricted double x, unrestricted double y, unrestricted double radius, unrestricted double startAngle, unrestricted double endAngle, optional boolean anticlockwise = false);   void ellipse(unrestricted double x, unrestricted double y, unrestricted double radiusX, unrestricted double radiusY, unrestricted double rotation, unrestricted double startAngle, unrestricted double endAngle, optional boolean anticlockwise = false); };  [Exposed=(Window,Worker)] interface CanvasGradient {   // opaque object   void addColorStop(double offset, DOMString color); };  [Exposed=(Window,Worker)] interface CanvasPattern {   // opaque object   void setTransform(optional DOMMatrix2DInit transform = {}); };  [Exposed=(Window,Worker)] interface TextMetrics {   // x-direction   readonly attribute double width; // advance width   readonly attribute double actualBoundingBoxLeft;   readonly attribute double actualBoundingBoxRight;    // y-direction   readonly attribute double fontBoundingBoxAscent;   readonly attribute double fontBoundingBoxDescent;   readonly attribute double actualBoundingBoxAscent;   readonly attribute double actualBoundingBoxDescent;   readonly attribute double emHeightAscent;   readonly attribute double emHeightDescent;   readonly attribute double hangingBaseline;   readonly attribute double alphabeticBaseline;   readonly attribute double ideographicBaseline; };  [Constructor(unsigned long sw, unsigned long sh),  Constructor(Uint8ClampedArray data, unsigned long sw, optional unsigned long sh),  Exposed=(Window,Worker),  Serializable] interface ImageData {   readonly attribute unsigned long width;   readonly attribute unsigned long height;   readonly attribute Uint8ClampedArray data; };  [Constructor(optional (Path2D or DOMString) path),  Exposed=(Window,Worker)] interface Path2D {   void addPath(Path2D path, optional DOMMatrix2DInit transform = {}); }; Path2D includes CanvasPath;
                                            ^ Missing return type
    at W.error (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:16191)
    at parse (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:10125)
    at Function.parse (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:19679)
    at Function.parse (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:22450)
    at o (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:26974)
    at i (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:27139)
    at c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:27435
    at te (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:27564)
    at ne (c:\Users\Adrian\Documents\GitHub\idl\node_modules\webidl2\dist\webidl2.js:1:27718)
    at Object.<anonymous> (c:\Users\Adrian\Documents\GitHub\idl\parse.js:242:14)
c:\Users\Adrian\Documents\GitHub\idl>`

**Comment by saschanaz** [comment]
Ah! You can't just do `.replace(/\r?\n|\r/g, " ");` because the IDL contains some inline comments. (Those comments will invalidate everything after them!) Try removing that `replace()` and parse the IDL again.

**Comment by am06** [comment]
thanks buddy, that worked! would have never figured that one out ;) 

now I'll need to figure out my next steps from here :D

one more thing, If I want to parse more IDLs (latest versios, not 4 year old:D ), where could I get a list from?

Cheers!

**Comment by saschanaz** [comment]
https://github.com/tidoust/reffy-reports/tree/master/w3c/idl has latest IDLs auto-collected for you 😀

**Comment by am06** [comment]
cheers, you're a life saviour ! 👍

**Comment by saschanaz** [comment]
Happy to assist you! I'm closing this, feel free to ask questions when you get new problems related to webidl2.js!
