### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by am06** [w3c/webidl2.js#414]
Hi,

so I was expecting that after I parse the IDL, I'd see a programtic description of classed/interface/methods (return type, params etc).........but I don't see that.

What am I missing, do I need to add some custom code?

Thanks,
A

**Comment by marcoscaceres** [comment]
try adding console.log() around parse().

**Comment by am06** [comment]
I did and I get something like this:

[ X {
    members: [ [g], [g], [b], [b], [b], [b] ],
    extAttrs: y [ f {}, f {}, f {} ] },
  C { values: [ _ {}, _ {} ], extAttrs: y [] },
  Q { members: [ [K], [K] ], extAttrs: y [] },
  F {
    idlType: l { extAttrs: y [], type: 'typedef-type' },
    extAttrs: y [] },
  X { members: [ [g], [g] ], extAttrs: y [ f {}, f {}, f {} ] },
  Q { members: [ [K] ], extAttrs: y [] },
  X { members: [ [b], [g] ], extAttrs: y [ f {}, f {} ] },
  X {
    members:
     [ [b],
       [b],
       [b],
       [b],
       [b],
       [B],
       [B],
       [B],
       [g],
       [g],
       [g],
       [g],
       [g],
       [g],
       [g],
       [g],
       [g] ],
    extAttrs: y [ f {}, f {} ] },
  X { members: [ [b], [b], [b], [b] ], extAttrs: y [ f {}, f {} ] },
  X { members: [ [b], [b] ], extAttrs: y [ f {} ] } ]


I can't make any sense out of this.

**Comment by saschanaz** [comment]
Yes... Currently webidl2.js is not very console.log-friendly. Should probably add some webpack flag to prevent the name mangling.

**Comment by am06** [comment]
so, can I get any info out of this?

**Comment by saschanaz** [comment]
For now, try `JSON.stringify(yourParsedResult, null, 2)`, which should emit some readable data.

**Comment by marcoscaceres** [comment]
@am06 to understand the structure, see the readme: https://github.com/w3c/webidl2.js/blob/gh-pages/README.md

**Comment by am06** [comment]
many thanks chaps. 

@marcoscaceres yeah I knew about that doc, seen it previously and now I'll look at it again to make more sense. That is the output I was hoping to get at, but I didn't see JSON.stringify documented anywere.

Cheers.
