### ISSUE TITLE
Be more console.log friendly

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#415]
Currently `console.log(parsedResult)` is hard to read because:

* class names are mangled (fix by #429)
* and the getters are not enumerated.

And this makes debug harder.

The first one should probably be fixed by some Webpack configuration field, but not sure about the second one.

**Comment by TG1999** [comment]
Hi ,I want to work on this issue can you guide me how can I proceed on it. And on which files of codebase I have to work so this issue can be solved.

**Comment by saschanaz** [comment]
We should probably modify https://github.com/w3c/webidl2.js/blob/gh-pages/webpack.config.js to prevent class name mangling. Haven't explored any actual options, though.

**Comment by saschanaz** [comment]
Continuing from #427:

Per https://webpack.js.org/plugins/terser-webpack-plugin/, it seems we can insert this in https://github.com/w3c/webidl2.js/blob/gh-pages/webpack.config.js:

```
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          output: {
            keep_classnames: true
          }
        }
      )
    ]
  }
```

This is supposed to fix this issue but I haven't test it. Since you can write a test, we can check whether this works as intended 👍

**Comment by TG1999** [comment]
Okay I am starting to work on this 😊

**Comment by saschanaz** [comment]
Let's just prefer ESM 😁 #556
