### ISSUE TITLE
Disallow Promise types inside unions

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#430]
See also https://github.com/heycam/webidl/pull/746

**Comment by saschanaz** [comment]
@TG1999 Wanna try this one?

We currently disallows `any` inside a union, but now we also want to disallow `Promise<>` there. The relevant line is:

https://github.com/w3c/webidl2.js/blob/7fb1c2f1c4fb5390e9e0239cb3978bbe4f30cc4c/lib/productions/type.js#L93

We probably want to check `if (typ.generic === "Promise")` and then throw.

The test for this is different from what you did yesterday. We want to:

* Add a file in [test/invalid/idl/](https://github.com/w3c/webidl2.js/tree/gh-pages/test/invalid/idl) that includes a wrong syntax. `typedef (Promise<DOMString> or boolean) Typedef;` should be sufficient.
* Run `npm run acquire` to generate baseline files
* Check that we got a new file in `test/invalid/baseline` with the expected error message.

**Comment by TG1999** [comment]
Yeah sure I don't have access to my system right now, will start work on it after 12 hours.

**Comment by TG1999** [comment]
Hi I am back ,I am currently adding line 94 as if (typ.generic==="Promise") tokeniser.error("Type `any` cannot be included in a union type");

**Comment by saschanaz** [comment]
Closed by #435
