### ISSUE TITLE
`any` is not a keyword

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#436]
But it should be!

**Comment by TG1999** [comment]
Can I work on this @saschanaz

**Comment by saschanaz** [comment]
Sure! 👍

The expected steps are:

1. Insert `"any"` to [`nonRegexTerminals`](https://github.com/w3c/webidl2.js/blob/gh-pages/lib/tokeniser.js#L56)
2. Write a test file as you did in #435. The content would be `interface any {};`
3. Generate the result by `npm run build && npm run acquire` but make sure you don't commit the `dist` files!

Maybe already too easy for you 😁

Some more advice:

1. Try writing a PR title based on [Angular commit message conversions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153). `fix: disallow promises from unions` for example.
2. Try keeping code formats consistent. For example, we prefer `if (true)` rather than `if(true)`.

**Comment by TG1999** [comment]
Thanks @saschanaz for this :smile:

**Comment by TG1999** [comment]
WebIDLParseError: Syntax error at line 10 in attributes.webidl, since `interface Person`:
  attribute any required ;
            ^ Attribute lacks a type
It is throwing this error while doing npm acquire

**Comment by saschanaz** [comment]
Oh right, we should explicitly allow `any` in `lib/productions/type.js`.

https://github.com/w3c/webidl2.js/blob/00f0647de818b707c68c62fb957f9d91e706a355/lib/productions/type.js#L65

We should add `"any"` in this line.

**Comment by saschanaz** [comment]
While you are at it, you could solve #251 with the same method here.

Additionally I found that we should also mark `"object"` and `"symbol"` as keywords, too.
