### ISSUE TITLE
More permissive extended attributes grammar

### ISSUE THREAD

**Issue by TimothyGu** [w3c/webidl2.js#455]
We would like to use some extended attribute types in jsdom, but that webidl2.js cannot currently parse.

```webidl
interface HTMLMyElement {
  // List of strings (from https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/bindings/IDLExtendedAttributes.md#reflectonly_a)
  [Reflect, ReflectOnly=("first", "second", "third", "fourth")] attribute DOMString quarter;

  // List of integers
  [Reflect, ReflectRange=(1, 4)] attribute unsigned long span;
};
```

----

#222 looked into changing the extended attributes parser to be more restrictive. heycam/webidl#574 resolved the question by saying that the grammar is intentionally generic. Indeed, the current [_ExtendedAttribute_](https://heycam.github.io/webidl/#prod-ExtendedAttribute) grammar allows for basically anything given that (quoting from #222):

> Any types of brackets must be closed if appears. Commas are allowed only inside brackets (as any comma outside will be a separator for the extended attribute).

**Comment by saschanaz** [comment]
We had this on #256, back then we just decided to add the specific syntax rather than allowing everything the spec allows, because of implementation simplicity. Maybe we can do same here?

**Comment by domenic** [comment]
I think it would also be nice to have `[Reflect="for"]`, instead of the current workaround of `[Reflect=for]`.

Increasing the ad-hoc support to support consumers like jsdom or #256 seems reasonable to me.

**Comment by saschanaz** [comment]
`[Reflect="for"]` is already supported 👍

**Comment by saschanaz** [comment]
Is `ReflectRange` from Blink IDL BTW?

**Comment by domenic** [comment]
I don't think so; this is for our plans in jsdom, which we're using a testing ground with the hope of eventually incorporating it into the HTML Standard. https://github.com/jsdom/jsdom/pull/2790#issuecomment-573273605
