### ISSUE TITLE
Add Snyk bot for dependency updates

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#474]
Hi @siusin, 

Thanks for your previous help in #433! Per #473 we need to migrate to Snyk instead, could you enable Snyk in this repo and disable greenkeeper?

**Comment by siusin** [comment]
Hi @saschanaz ,

Greenkeeper is now disabled. I added this repo to the Snyk projects. Let me know if there is anything missing.

<img width="778" alt="Screenshot 2020-05-06 at 11 23 03 AM" src="https://user-images.githubusercontent.com/5643782/81135816-2eb48f80-8f8c-11ea-91fe-41a0a5e27228.png">

**Comment by saschanaz** [comment]
Yay, thank you very much!
