### ISSUE TITLE
Error when parsing sequence attribute

### ISSUE THREAD

**Issue by zhiyi01** [w3c/webidl2.js#479]
Hello, I'm trying to parse the demo.webidl 
```
[Exposed=Window]
interface Node {
  readonly attribute sequence<DOMString> states;
};
``` 
This issues likes https://github.com/w3c/webidl2.js/issues/477 ,but here is uesed `sequence<DOMString>`

```
Exception while parsing WebIDL. See JavaScript console for more details.

WebIDLParseError: Syntax error at line 4, since `interface Node`:
 attribute sequence<DOMString> states;
                               ^ Attributes cannot accept sequence types
```

**Comment by saschanaz** [comment]
It's exactly what the error says. Attributes can't use sequences, they instead should use FrozenArrays.

**Comment by marcoscaceres** [comment]
@zhiyi01 where did you get demo.webidl from?

**Comment by zhiyi01** [comment]
> @zhiyi01 where did you get demo.webidl from?

https://github.com/mozilla/gecko-dev/blob/master/dom/webidl/AccessibleNode.webidl#L12

**Comment by saschanaz** [comment]
Gecko doesn't support FrozenArray unfortunately 😬

**Comment by saschanaz** [comment]
The relevant Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1236777

You should manually replace the sequences to FrozenArrays until this is fixed.

BTW, it seems AccessibleNode is gone. https://wicg.github.io/aom/explainer.html#what-happened-to-accessiblenode

**Comment by saschanaz** [comment]
Closing as currently supporting implementation-specific IDL syntax is out of scope.
