### ISSUE TITLE
Parsing updated ecma262 intrinsic notation

### ISSUE THREAD

**Issue by ljharb** [w3c/webidl2.js#480]
Hi!

In the ecma262 spec, we've added a [new intrinsic notation form](https://github.com/tc39/ecma262/pull/1376) that will avoid unbounded growth of our list of intrinsics.

Specifically, things like `%ArrayPrototype%` and `%ObjProto_valueOf%` should now be represented as `%Array.prototype%` and `%Object.prototype.valueOf%`, respectively.

Our intention is to delete the "legacy" forms entirely in favor of the dotted forms. I wanted to file a PR on https://github.com/whatwg/html, but then realized I might need to file one on https://github.com/heycam/webidl/blob/master/index.bs#L88-L110, and then saw https://github.com/heycam/webidl#syntax-changes-should-be-filed-against-the-following-parsers and realized I might need to file one here.

I'm happy to do the work to update spec text (and for HTML, I have a branch prepared already), but I doubt I'm qualified to do the parser work. Could someone help give me pointers as to what the next steps should be?

**Comment by saschanaz** [comment]
Hi, thanks for opening this!

I guess this specific one should go heycam/webidl repo, as the ecma262 syntax change does not affect IDL syntax so no change is required for this library.

Since I have no write access there unfortunately, could you open a new issue there? Thanks!

**Comment by ljharb** [comment]
Absolutely, thanks :-) I was concerned there'd be parsing issues around `%A.b%` versus just `%A%`.

**Comment by ljharb** [comment]
Closing in favor of https://github.com/heycam/webidl/issues/897. Thanks for the quick reply!

**Comment by saschanaz** [comment]
Thanks! I see JSON.stringify is already in that list so it shouldn't break anything.
