### ISSUE TITLE
Unnecessarily dismissive wording in README

### ISSUE THREAD

**Issue by brainkim** [w3c/webidl2.js#502]
> This is a parser for the Web IDL language. If you don't know what that is, then you probably don't need it.

Maybe I’m being overly sensitive, but the tone of the second sentence manages to be both dismissive and snobbish, which is not a good look for an official w3c project. Perhaps a short sentence summarizing what Web IDL is would be more appropriate 🙂🙃

**Comment by saschanaz** [comment]
Yes, I think it's not W3Cish and purely redundant. A link to the introduction section of the Web IDL spec should be enough. Thank you for raising this!
