### ISSUE TITLE
Sunset UMD support

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#514]
[Node.js 15.3.0 marked ESM support as stable](https://github.com/nodejs/node/pull/35781). Since Node.js and browsers have supported ESM for years (with two Node.js LTS versions), it should be okay to sunset the UMD one.

See also #494

**Comment by saschanaz** [comment]
Hey @foolip, would this be okay for WPT and the BCD collector?

**Comment by foolip** [comment]
I'm sure I can adapt mdn-bcd-collector to whatever the change is, but for WPT I'm not sure. Will the generated script we use be different in some way?

**Comment by saschanaz** [comment]
Yeah, sunsetting UMD will force the consumers to use ES module instead. For Node.js I guess it hopefully shouldn't be a breaking change unless anyone is still using pre-module version of Node.js (... that is Node 12, which still is an active LTS. 🤔), but in browsers `<script module>` will be required. The simplest way would be:

```diff
- <script src=/resources/WebIDLParser.js></script>
+ <script module>
+ import * as WebIDL2 from "/resources/webidl2/lib/webidl2.js";
+ globalThis.WebIDL2 = WebIDL2;
+ </script>
```

All targets of WPT support `<script module>` by now, right?

**Comment by foolip** [comment]
`<script type=module>` is supported in all browsers that we run WPT on and I do see it used elsewhere in WPT. I expect it would be a fair amount of work since there's a mix of handwritten and generated idlharness.js tests, so I expect we'd just not upgrade until a new webidl2.js release is absolutely required.

**Comment by saschanaz** [comment]
This isn't doable without a serious breaking change since `require()` in Node.js cannot import ESM. CommonJS use is still allowed with #565 and it will be kept that way at least in the foreseeable future.
