### ISSUE TITLE
module not supported?

### ISSUE THREAD

**Issue by developerlaoz** [w3c/webidl2.js#52]
Excuse me, I try the this parser on https://github.com/RicoP/idl2typings/blob/master/idl/webgl.idl, and get Exception of 
"Unrecognised tokens, line 14 (tokens: 'module webgl {')"

Does module not supported yet？

**Comment by marcoscaceres** [comment]
I don't think "module" is a thing in WebIDL? 
https://heycam.github.io/webidl/

Are you sure that is WebIDL?

**Comment by developerlaoz** [comment]
I am sorry. 
"module" exists in https://www.w3.org/TR/2008/WD-WebIDL-20080829.
But  I check the https://www.w3.org/TR/WebIDL, there is no "module" now.
I think I choose the old idl file. Thank you.

**Comment by marcoscaceres** [comment]
No problem. Good luck!
