### ISSUE TITLE
Add BigInt64Array and BigUint64Array types

### ISSUE THREAD

**Issue by TimothyGu** [w3c/webidl2.js#600]
URL: https://github.com/heycam/webidl/pull/936

I'm not sure if this should be considered a breaking change, and so I removed the BREAKING CHANGE prefix.

cc: @marcoscaceres @sidvishnoi for ReSpec

**Comment by marcoscaceres** [comment]
Thanks @TimothyGu! Doesn't look like a breaking change. Just an addition of some interfaces, right?
