### ISSUE TITLE
Why is the record<K, V> invalid?

### ISSUE THREAD

**Issue by ntcmp2u** [w3c/webidl2.js#613]
idl file: 
```
interface TypeConversions {
    undefined setTestLongRecord(record<DOMString, long> record);
}
```

while the idl parser complains:

```
WebIDLParseError: Syntax error at line 2, since `interface TypeConversions`:
    undefined setTestLongRecord(record<DOMString, long
                                ^ Unterminated operation
```

I think the idl file well follows the webidl standard (https://heycam.github.io/webidl/#idl-record). Is there anything I misunderstand?

**Comment by saschanaz** [comment]
Probably the parameter name, since `record` is a keyword. The message is arguably not helpful here 😬

**Comment by ntcmp2u** [comment]
Oh I see. thanks!
