### ISSUE TITLE
Whitespace issues

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#64]
@dontcallmedom, I'm getting breakages in the ReSpec test suite relating to white space going missing. Could you possibly help debug that? 

I'm won't have time to look at it for 2 weeks (going on vacation) - so can't release an updated ReSpec to support the latest changed recently added. 

Ping me on IRC if you want to discuss... otherwise, just run the test runner in ReSpec and you will see the errors. 

E.g., 

```
Expected '        typedef DOMString string;
      ' to equal 'typedef DOMString string;'.
```

**Comment by SaschaNaz** [comment]
Not tested yet, but [the template for typedef](https://github.com/w3c/respec/blob/1805d098d6a204463177a7f45d95d3011681c64c/js/core/templates/webidl-contiguous/typedef.html) on ReSpec refers `typeExtAttrs` which is a removed property on 2.4.0. Maybe a possible reason?

**Comment by marcoscaceres** [comment]
@SaschaNaz, thanks for the pointer to investigate!

**Comment by marcoscaceres** [comment]
@SaschaNaz, you were spot on. That was the problem. Upgrading ReSpec to 3.0.1.
