### ISSUE TITLE
Remove exceptions support

### ISSUE THREAD

**Issue by markandrus** [w3c/webidl2.js#65]
webidl2.js includes [a function for parsing exceptions](https://github.com/w3c/webidl2.js/blob/a0bccdf485a511a94042d8d541a9cfbcc7de15c3/lib/webidl2.js#L919) (I even went so far as to type these as `IDLException` in [my typed branch](https://github.com/w3c/webidl2.js/pull/55)); however, upon closer inspection, I don't believe WebIDL allows exceptions to be declared. See [here](https://www.w3.org/TR/2016/PR-WebIDL-1-20160915/#idl-exceptions): 

> An **exception** is a type of object that represents an error and which can be thrown or treated as a first class value by implementations. Web IDL does not allow exceptions to be defined, but instead has a number of pre-defined exceptions that specifications can reference and throw in their definition of operations, attributes, and so on.

I also don't see any reference to "exception" in the grammar, so I think this code should be removed (originally introduced [here](https://github.com/w3c/webidl2.js/commit/da8ef5ea208a981b99d60bcf54c64b408175490a)).

**Comment by marcoscaceres** [comment]
yeah, you used to be able to define exceptions many years ago. That's all dead code likely.
