### ISSUE TITLE
package.json module causing error in importmap-node module. Maybe invalid?

### ISSUE THREAD

**Issue by goldingdamien** [w3c/webidl2.js#721]
When I was testing using https://github.com/jsenv/importmap-node-module , an error occurred due to webidl2 because of "module" in package.json. Please check that it is OK. Regards.

**Comment by goldingdamien** [comment]
When installing this library, the package.json in node_modules contains module: "index.js". However, there is nothing at index.js. https://github.com/jsenv/importmap-node-module works by going through all node_modules packages and building a map of imports.

※ I am not very familiar with the specification of "module" so I am not sure if the issue is with https://github.com/jsenv/importmap-node-module instead, but no other packages were affected, so it is my assumption that module is invalid.
※ This is not a vital issue, but if it is a problem with the package.json, then it would be appreciated if it could be checked up on when possible.
Regards.

**Comment by saschanaz** [comment]
I don't think it's this package, because if so it should have been broken for everyone. I'd recommend you to file an issue there.

>However, there is nothing at index.js.

That makes no sense, maybe a faulty installation?

**Comment by goldingdamien** [comment]
No, I think the package parses the data from node_modules so, it is probably not loading through any normal mechanism.
I assume normally "main" is used, but "module" is not. "main" is working fine, it is only "module" that had an issue(format of package.json in node_modules is different to that before building).
It is OK if you do not consider it an important issue. I thought I should share here first.
I'll close the issue here and enquire with the other package repository.
Thank you for your time.

**Comment by saschanaz** [comment]
> It is OK if you do not consider it an important issue. I thought I should share here first.

I'm all for solving issues, I just think it's not this package's fault. I hope you can get some solution there 👍
