### ISSUE TITLE
Should report error for using duplicate names

### ISSUE THREAD

**Issue by vivekgalatage** [w3c/webidl2.js#77]
Consider the following example idl:

```webidl
typedef int Test;

interface Test {
  void foo();
};

```

The generated output is as
```json
[
    {
        "extAttrs": [],
        "idlType": {
            "generic": null,
            "idlType": "int",
            "nullable": false,
            "sequence": false,
            "union": false
        },
        "name": "Test",
        "type": "typedef"
    },
    {
        "extAttrs": [],
        "inheritance": null,
        "members": [
            {
                "arguments": [],
                "creator": false,
                "deleter": false,
                "extAttrs": [],
                "getter": false,
                "idlType": {
                    "generic": null,
                    "idlType": "void",
                    "nullable": false,
                    "sequence": false,
                    "union": false
                },
                "legacycaller": false,
                "name": "foo",
                "setter": false,
                "static": false,
                "stringifier": false,
                "type": "operation"
            }
        ],
        "name": "Test",
        "partial": false,
        "type": "interface"
    }
]
```

In this case, the name `Test` is used twice: once for the interface and once for the typedef.

Should the library report this as an error?

**Comment by marcoscaceres** [comment]
It's a tough call because IDL fragments are, more often then not, parsed independently - so this would have limited value to some applications (e.g., in ReSpec). 

However, in cases where lots of fragments are parsed at once (and it would be a nice feature for validation/linting), thus I can certainly see the utility. 

Having said that, does the IDL spec forbid duplicate identifiers even when different types? (I guess it probably should, just not sure).

**Comment by TimothyGu** [comment]
Yes it does. https://heycam.github.io/webidl/#idl-names

> Within the set of IDL fragments that a given implementation supports, the identifier of every interface, namespace, dictionary, enumeration, callback function and typedef must not be the same as the identifier of any other interface, namespace, dictionary, enumeration, callback function or typedef.

**Comment by marcoscaceres** [comment]
Ok, thanks for confirming @TimothyGu.
