### ISSUE TITLE
Update ongoing promise in async iterator `return()` method

### ISSUE THREAD

**Issue by MattiasBuelens** [w3c/webidl2.js#770]
There's an edge case with [the current Web IDL bindings for async iterators](https://webidl.spec.whatwg.org/commit-snapshots/47c5c920811b1bfdd56304a9d8313766d482897b/#ref-for-asynchronous-iterator-return) where manually calling `return(); next()` could result in the `next()` promise resolving before the `return()` promise. The latest version of the Web IDL specification fixes this by updating the "ongoing promise" in the async iterator `return()` method.

* [Web IDL spec change](https://github.com/whatwg/webidl/pull/1387)
* [Web platform tests](https://github.com/web-platform-tests/wpt/pull/44456) (for `ReadableStream[@@asyncIterator]`)

**Comment by MattiasBuelens** [comment]
Apologies, I mean to file this bug on the (very similarly named) [webidl2js](https://github.com/jsdom/webidl2js) project. 😅

Since the aforementioned spec change does not affect the Web IDL syntax, no action needs to be taken on the part of webidl2.js. Closing.

**Comment by saschanaz** [comment]
Haha that often confused myself too 😂
