### ISSUE TITLE
test clarification: invalid/sharedarraybuffer

### ISSUE THREAD

**Issue by nektro** [w3c/webidl2.js#786]
https://github.com/w3c/webidl2.js/blob/91b2878/test/invalid/idl/sharedarraybuffer.webidl#L1

```webidl
interface SharedArrayBuffer {};
```

```
WebIDLParseError: Syntax error at line 2:
interface DOMString {};
          ^ Missing name in interface
```

on first glance it seems like this should work with `SharedArrayBuffer` being validly parsed as an identifier like so:
[Definitions](https://webidl.spec.whatwg.org/#index-prod-Definitions)
[Definition](https://webidl.spec.whatwg.org/#index-prod-Definition)
[CallbackOrInterfaceOrMixin](https://webidl.spec.whatwg.org/#index-prod-CallbackOrInterfaceOrMixin)
[InterfaceOrMixin](https://webidl.spec.whatwg.org/#index-prod-InterfaceOrMixin)
[InterfaceRest](https://webidl.spec.whatwg.org/#index-prod-InterfaceRest)
[identifier](https://webidl.spec.whatwg.org/#prod-identifier)

this led me to believe perhaps types defined by IDL itself are disallowed? but `interface int {};` passes
maybe just the types `[Exposed]`? closer `interface DOMString {};` does fail

is there a section where this is outlined which exact union of types throws an error and/or is this a bug in the library?

**Comment by saschanaz** [comment]
`int` is not a keyword (you need to do `short` or `long`) but SharedArrayBuffer is. Same for DOMString.

**Comment by nektro** [comment]
ah good catch. so its all keywords?

**Comment by saschanaz** [comment]
yup.

**Comment by nektro** [comment]
this is now resolved and correctly failing on my end. thank you :)
