### ISSUE TITLE
test clarification: multiple 'valid' syntax cases use legacy extended attributes

### ISSUE THREAD

**Issue by nektro** [w3c/webidl2.js#787]
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/identifier-hyphen.webidl
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/namedconstructor.webidl
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/nointerfaceobject.webidl
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/overridebuiltins.webidl
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/treatasnull.webidl

all of these throw validation errors when passed through the [checker](https://w3c.github.io/webidl2.js/checker/).

this is corroborated by https://github.com/w3c/webidl2.js/blob/91b2878/test/invalid/idl/renamed-legacy-extattrs.webidl
and https://github.com/whatwg/webidl/pull/870

> ^ `[TreatNullAs]` extended attribute is a legacy feature that is now renamed to `[LegacyNullToEmptyString]`. Refer to the [relevant upstream PR](https://github.com/whatwg/webidl/pull/870) for more information.

is this an issue or a detail i'm missing?

**Comment by saschanaz** [comment]
That "syntax" tests are literally just syntax tests, having a wrong extended attribute shouldn't make a syntax issue. They still may make some validation issues, but that's fine.

**Comment by nektro** [comment]
ohhh i see.
