### ISSUE TITLE
test clarification: multiple 'valid' cases use constructor extended attribute

### ISSUE THREAD

**Issue by nektro** [w3c/webidl2.js#788]
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/stringifier-attribute.webidl
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/stringifier-custom.webidl
https://github.com/w3c/webidl2.js/blob/91b2878/test/syntax/idl/record.webidl

all of these throw validation errors when passed through the [checker](https://w3c.github.io/webidl2.js/checker/).

this is corroborated by https://github.com/w3c/webidl2.js/blob/91b2878/test/invalid/idl/constructor.webidl

> ^ Constructors should now be represented as a `constructor()` operation on the interface instead of `[Constructor]` extended attribute. Refer to the [WebIDL spec section on constructor operations](https://webidl.spec.whatwg.org/#idl-constructors) for more information.

is this an issue or a detail i'm missing?

**Comment by saschanaz** [comment]
Same as #787, those are just syntax tests.
