### ISSUE TITLE
[Bug] w3c webref repo contains "implements" in some files.

### ISSUE THREAD

**Issue by cyraid** [w3c/webidl2.js#795]
I read on one pull request that `implements` was removed? In the repo:

https://github.com/w3c/webref/blob/429ee9f4891ee37e467f3d8e8fbe1ab193cabd2e/tr/idl/cssom-view.idl#L175

```idl
Text implements GeometryUtils; // like Range
```

There are 4 statements that use `implements`, and WebIDL2 parser just won't have it. Should there be a filing on that repo? Or is there something we can do for this one?

For now, what would be the recommended approach or workaround?

**Comment by saschanaz** [comment]
You probably dont' want to consume /tr/idl as they are old. Try using ed/idl instead.

**Comment by cyraid** [comment]
But ed/idl for example, has things like `CSSMarginRule.CSSMarginDescriptors` (in ed/idl/cssom.idl), which CSSMarginDescriptors doesn't exist as for as a search goes.

**Comment by saschanaz** [comment]
Oh, good catch. CSSMarginDescriptors is being used in https://drafts.csswg.org/cssom/ without being defined, that's why it doesn't exist in ed/idl. Can you file an issue in https://github.com/w3c/csswg-drafts/issues ?

**Comment by dontcallmedom** [comment]
there is already an issue for this FWIW https://github.com/w3c/csswg-drafts/issues/10106

(we [patch the CSSOM IDL in webref](https://github.com/w3c/webref/blob/204b94c0de643a4653b706b2f50a1a7d998b6f03/ed/idlpatches/cssom.idl.patch#L7) for that very reason)
