### ISSUE TITLE
[NoInterfaceObject] on Dictionary types

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#81]
We should probably abort if we see `[NoInterfaceObject]` on a Dictionary. Just saw this in spec I was reviewing.

**Comment by SaschaNaz** [comment]
Do we want to apply strict restrictions for other extended attributes? E.g. [`A type that is not a buffer source type must not be associated with the [AllowShared] extended attribute.`](https://heycam.github.io/webidl/#AllowShared)

**Comment by marcoscaceres** [comment]
For validation purposes, that would be pretty useful.

**Comment by marcoscaceres** [comment]
No longer relevant
