### ISSUE TITLE
Drop support for Node 4, move to 6 LTS

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#82]
In October, we should drop Node 4, and start targeting. 

It might also be a good chance to rewrite this is ES6. 

Would like to be part of that effort so I can learn the code base a bit better.

**Comment by SaschaNaz** [comment]
I agree with the issue but is there a specific reason why October? I thought the end of maintenance was October but it wasn't.

**Comment by TimothyGu** [comment]
That's when 8.x gets into LTS. Usually it's a good practice to support two LTS branches at any given point of time.

**Comment by marcoscaceres** [comment]
> I agree with the issue but is there a specific reason why October? I thought the end of maintenance was October but it wasn't.

It's end of October. I don't mind supporting LTS 6 - as we still get everything we need.
