### ISSUE TITLE
Type conversion on default values is destructive 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#94]
Given 

```
interface X {
  const unsigned long BIT_MASK = 0x0000fc00;
}
```

Becomes:

```
"{
  "type": "number",
  "value": 64512
}"
```

I think the only fix here is not to do the number conversion. 

@SaschaNaz, thoughts?

**Comment by SaschaNaz** [comment]
👍 

```json
{
  "type": "number",
  "value": 64512,
  "raw": "0x0000fc00"
}
```

Alternatively we can add `base: 16` thing but that won't recover preceding zeros, which may be a problem in some situation.

**Comment by marcoscaceres** [comment]
I like the “raw” member, but I’m still not entirely sure of the use case for doing the conversion during parse. It seems that if a consumer has type “number” and “value”, they can perform the conversion themselves.

**Comment by marcoscaceres** [comment]
Apologies, I see you answered the above in the PR. 🙏

**Comment by SaschaNaz** [comment]
Yeah, the conversion is reasonably easy so it shouldn't be a big issue for users who uses the resulting number value for whatever reason.
