### ISSUE TITLE
Remove implements statement support

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#98]
I think "implements" has been dropped from the IDL spec... probably when "mixin" happened... 

Affected specs: https://github.com/heycam/webidl/issues/472

**Comment by tobie** [comment]
Yes. I'm overdue filing bugs for this. I'll look into it today. Sorry. :-/

**Comment by marcoscaceres** [comment]
Np at all. If it’s a “yes”, than I’m happy to pull support. But I guess we should add in mixin support at the same time?

**Comment by tobie** [comment]
Can we sync up on this issue?

**Comment by tobie** [comment]
Sorry, fat fingered this.

**Comment by TimothyGu** [comment]
Would be nice to have a period of time when both implements statements and mixins are supported to ease transition.

**Comment by marcoscaceres** [comment]
> Would be nice to have a period of time when both implements statements and mixins are supported to ease transition.

The following tests/specs things would break:

- [ ] cssom-view
- [ ] cssom
- [ ] dedicated-workers
- [ ] dom
- [ ] html
- [ ] mediacapture-main

So we should get those migrated first.

**Comment by marcoscaceres** [comment]
(the list above is not complete... it's what I got from `git grep --name-only implements ./interfaces` on the WPT repo)

**Comment by marcoscaceres** [comment]
@TimothyGu, could you help us notify those spec owners that we plan on making this breaking change? Probably cc @tobie, as editors might need help with reviews when adding the new syntax... otherwise, we can send PRs for the affected specs, as it's only a syntax change to the IDL in most cases, and should not affect any prose.

**Comment by marcoscaceres** [comment]
I've moved the list of affected specs to the top of this bug... we can cross them off as they get merged.

**Comment by TimothyGu** [comment]
@marcoscaceres Filed some bugs.

**Comment by tobie** [comment]
So just FYI, I've built a system to automate the bug filing and tracking for WebIDL changes in the future, hence the delay in doing this here. I know this delays things a bit, and I'm sorry about it.

**Comment by tobie** [comment]
Problem is we're now going to have plenty of dups. So if you could off adding more issues, that would really help.

**Comment by TimothyGu** [comment]
@tobie Sorry about that.

**Comment by tobie** [comment]
Yeah, I should have finished this way earlier. :-/

**Comment by tobie** [comment]
Thanks!

**Comment by marcoscaceres** [comment]
@tobie that's awesome to hear about the automated bug filing. @TimothyGu apologies for asking you to do needless work :(

**Comment by tobie** [comment]
OK, finally shipped this. You can track all the things from here: heycam/webidl#472.
